### ISSUE TITLE
error reading row with invalid date

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#104]
I am running into an issue reading a spreadsheet row that has an invalid date in it - not sure if it's an issue with php-excel or libxl.

There is a reproduce xlsx file at https://drive.google.com/uc?export=download&id=0B37DKbJklxg_aktOc09vX0xha0U.

In the below script, the var_dump returns false.  As I was making the above test case, I also received errors of "zend_mm_heap corrupted" and "Segmentation fault", depending on the input xlsx file.

```
<?php
$libxl = new ExcelBook('', '', true);

$libxl->loadFile('Book1.xlsx');

$worksheet = $libxl->getSheet(0);

var_dump($worksheet->readRow(1));
```

**Comment by iliaal** [comment]
While that would be really handy expansion on the error message, we are limited by what libxl is making available. Until libxl provides more details on the error we can't do much here
