### ISSUE TITLE
fatal error reading xlsx file

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#105]
Relating to issue #104, here is one example where I got a fatal error when reading a xlsx file.

There is a reproduce xlsx file at https://drive.google.com/uc?export=download&id=0B37DKbJklxg_bEh3TGVkWDdRZU0.

Run the below script using the command:

```
php -n -d extension=excel.so -d log_errors=On -d error_log=./log.txt script.php
```

When I run it, I get the following in log.txt:

```
[14-Nov-2014 04:00:07 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 140078141677584 bytes) in Unknown on line 0
```

I'm still working on a reproduce xlsx to generate a segfault, but the above might be the same underlying issue.

```
<?php
$libxl = new ExcelBook('', '', true);

$libxl->loadFile('Book2.xlsx');

$worksheet = $libxl->getSheet(0);

$row = 1;

while ($row < $worksheet->lastRow())
{
	if ($worksheet->readRow($row) === false)
	{
		echo 'false';
		exit;
	}

	$row++;
}
```

**Comment by iliaal** [comment]
I don't see a crash with PHP7 build of libxl I suspect it maybe related to 32/64bit issues I fixed in that build earlier.
