### ISSUE TITLE
reading cells with false

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#107]
Very minor edge case - just curious if there is a way around it:

I was reading a excel file that had the value FALSE in a cell.  The result of calling read() was false (bool).

I believe the function read() also returns false if there is an error reading a cell.  I have error handling set-up in my script to stop execution if read() returns false since I thought that indicated an error.

Is there a way to differentiate between reading a cell with a value of false and getting an error reading a cell?

There is a reproduce xlsx file at https://drive.google.com/uc?export=download&id=0B37DKbJklxg_N29hUWFwSUtfS2M.

Reproduce script is:

```
<?php
$libxl = new ExcelBook('', '', true);

$libxl->loadFile('Book3.xlsx');

$worksheet = $libxl->getSheet(0);

var_dump($worksheet->read(1, 0));
```

**Comment by iliaal** [comment]
You can use the getError() method from the Book to do what you've done with JSON extension. We don't want to call the method on each read internally as that would slow down the reading unnecessarily in all cases
