### ISSUE TITLE
How to read big numbers?

### ISSUE THREAD

**Issue by italotasso** [iliaal/php_excel#112]
In a cell I have the number 25755830000445700. When I read it with $sheet->read($row, $col) I get 2.5755830000446E+16 instead.

How do I read the actual number, as a string, instead of it formatted in scientific notation?

**Comment by johmue** [comment]
If the field is formatted as a number in Excel it is afaik not possible to read the number as string which lead to imprecisions due to the data types used in C / PHP.

**Comment by iliaal** [comment]
Large numbers are converted to Floats and PHP formats large floats in the manner you describe. I'm afraid this is nothing something we can change.
