### ISSUE TITLE
Result of readrow only the formula

### ISSUE THREAD

**Issue by rvdsarr** [iliaal/php_excel#116]
Hey guys,

I got the extension working, and bought a license of Libxl. It's working perfectly, except for sheet where the value of a cell is a formula.

I would need the result of the formula to show, instead of the actual formula. 

I've looked through the docs but I was unable to find a solution to this. I tried setting read_formula to false, but that didnt work.

Do you have any tips on how to handle this?

Thanks in advance!

Roy

**Comment by johmue** [comment]
Hi,

checked with the actual version and the tagged version 1.0.

I am not able to reproduce your results. It reads formula as well as values. Please keep in mind that files build with LibXL include only formulas unless you open and re-save them with Excel (see also section "Known Issues" in the README).

``` php
$b = new ExcelBook(null, null, true);
$b->loadFile('Issue116.xlsx');

$s = $b->getSheet(0);
var_dump($s->readRow(3, 0 , -1, false)); // row 4 includes a formula in test file
```
