### ISSUE TITLE
PECL Module

### ISSUE THREAD

**Issue by segadora** [iliaal/php_excel#124]
Is it possible to use php_excel as a pecl module?

**Comment by iliaal** [comment]
You mean install it via PECL?

**Comment by segadora** [comment]
yes

**Comment by iliaal** [comment]
You can do the following:

pear install path-to-tar-file

**Comment by segadora** [comment]
And the tar file includes the project?

Don't I have to define configurations and such?

**Comment by iliaal** [comment]
You can use the tarball from the release, https://github.com/iliaal/php_excel/archive/1.0.1final.tar.gz

**Comment by segadora** [comment]
Okay, I will try it and report back.

**Comment by pirxthepilot** [comment]
Hello, I tried running `pear install 1.0.1final.tar.gz` but got this error:

```
parsePackageName(): "1.0.1final.tar.gz" is neither a valid version nor a valid state in "php_excel-1.0.1final.tar.gz"
could not extract the package.xml file from "php_excel-1.0.1final.tar.gz"
install failed
```
Am I doing something wrong?

**Comment by iliaal** [comment]
The 1.0.2 release now has pecl packages attached to it that can be installed using pear install package.tgz
