### ISSUE TITLE
Column auto-fit not working

### ISSUE THREAD

**Issue by ptejada** [iliaal/php_excel#125]
Calling `Excelsheet::setColwidth()` with a `-1` width throws the following warning:
```
ExcelSheet::setColWidth(): Width cannot be less then 0
```

**Comment by johmue** [comment]
Please try the latest LibXL release since the changelog suggests that they have improved auto-fitting. http://libxl.com/changelog.html

**Comment by lap-chan** [comment]
@johmue 

Is there any walkthrough on how to update libxl 3.6.2 from version 3.6.1? I've already run through the commands below but still can't get it updated.

```
phpize5 
./configure --with-excel --with-libxl-incdir=/home/user/libxl-3.6.2.0/include_c --with-libxl-libdir=/home/user/libxl-3.6.2.0/lib64
make
make test
make install
service apache2 restart
```

After executing all the commands above, by revisiting phpinfo page, the version number remains at **3060101**

Your help would be highly appreciated. Thanks in advance.

*L*

**Comment by belgattitude** [comment]
@lap-chan 

Currently running on libxl 3.6.2 without problems till now (ubuntu 14.04 - 64) and libxl version is correct (3060200). Any messages during make ?

![libxl362](https://cloud.githubusercontent.com/assets/259798/7585988/6b8edb52-f8a8-11e4-814d-5244da792568.jpg)

**Comment by johmue** [comment]
Looks good to me.

**Comment by lap-chan** [comment]
@belgattitude 

I've just got it resolved by executing `make clean` before `make` to wipe up the cache. And right now the libXL version turns to `3060200`. Thanks!
