### ISSUE TITLE
Fatal error: Class 'ExcelBook' not found

### ISSUE THREAD

**Issue by reviec** [iliaal/php_excel#126]
I downloaded the windows .dll-s, and copied them to the php extension fonder, and added this lines to the php.ini

[PHP_EXCEL]
extension=php_excel.dll
[libxl]
extension=libxl.dll

But still I get this error: Fatal error: Class 'ExcelBook' not found
The other extensions work, just the ExcelBook not. 
I use PHP 5.2.6

**Comment by johmue** [comment]
Hi @reviec please try again with an up-2-date PHP version (PHP 5.2.6 is from 2008!!). Anyways, please remove the second entry:

    [libxl]
    extension=libxl.dll

...and place the libxl.dll directly into the PHP directory. Make sure the PHP directory is set in your PATH environment variable. Please also check if the excel extension is loaded with the cli command ```php.exe -m```. It could be also possible that your PHP is loading a different php.ini, you can check with ```php.exe -ini```. Most likely the extension is simply not compatible with PHP 5.2.6 but this is just a guess.

**Comment by lighter** [comment]
My os is win 7, xampp(v3.1.0), php(5.4.7). I download `php_excel-20140606-5.4-ts-vc9-x86`. 
1. Copy `libxl.dll` to `C:\xampp\apache\bin\` and `C:\xampp\php\`.
2. Copy `php_excel.dll` to `C:\xampp\php\ext\`.
3. add this to `php.ini`, and restart apache.

```
[excel]
extension=php_excel.dll
```

**Comment by ankesh4040** [comment]
Tried this:--

My os is win 7, xampp(v3.1.0), php(5.4.7). I download php_excel-20140606-5.4-ts-vc9-x86.

Copy libxl.dll to C:\xampp\apache\bin\ and C:\xampp\php\.
Copy php_excel.dll to C:\xampp\php\ext\.
add this to php.ini, and restart apache.
[excel]
extension=php_excel.dll

But I am getting apache error. Dynamic library not found!!

PHP Startup: Unable to load dynamic library 'php_excel.dll' (tried: c:\\xampp\\php\\ext\\php_excel.dll (The specified module could not be found.)
