### ISSUE TITLE
Read rows that don't have a foregroundfill. 

### ISSUE THREAD

**Issue by rvdsarr** [iliaal/php_excel#127]
Hello,

I'm trying to read rows only that are white and have no foregroundfill color. In het example excel sheet that means reading rows 1-4, 6-8 10-12 and 14-16.

Could you point me in the right direction on which code to use?

Thank you.

Kind regards, Roy
![naamloos](https://cloud.githubusercontent.com/assets/10889885/7546366/37d4f882-f5dd-11e4-8be8-b2994096f7d8.png)

**Comment by johmue** [comment]
You can adapt this code to your example...

```php
$xb = new ExcelBook(null, null, true);
$xb->setLocale('UTF-8');
$xb->loadFile('a.xlsx');

$xs = $xb->getSheet(0);

$lastRow = $xs->lastRow();

for ($rowIndex=0; $rowIndex < $lastRow; $rowIndex++) {
    $format = $xs->cellFormat($rowIndex, 0);
    
    if (ExcelFormat::COLOR_DEFAULT_FOREGROUND === $format->patternForegroundColor()) {
        print_r($xs->readRow($rowIndex));
    }
}
```

**Comment by rvdsarr** [comment]
Thank you very much :)
