### ISSUE TITLE
slow speeds writing null

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#128]
I am seeing slow speeds when trying to write the value null to a cell.  In the below example, please fill in your real license info.  For me, the script takes 16 seconds to run.  If I change $value to be the string 'test', then the script takes 0.4 seconds.  For now, I've updated my code to skip write calls when the value is null, but should the speed be the same when writing nulls?  Thanks for your help.

```
<?php
$libxl = new ExcelBook('', '', true);

$o_sheet = $libxl->addSheet('test');

$value = null;

for ($i = 0; $i < 1000; $i++)
{
	for ($j = 0; $j < 200; $j++)
	{
		$o_sheet->write($i, $j, $value);
	}
}
```

**Comment by johmue** [comment]
This is due to how the extension handles ```null``` values on writes internally. I had a quick look and there are two quick fixes you can choose:

```php
// skips writes on null values
ini_set('excel.skip_empty', 1);
```
or

```php
// prevents extension from creating a format on each iteration
$value = null;
$fakeFormat = new \ExcelFormat($libxl);
// [..]
$o_sheet->write($i, $j, $value, $fakeFormat);
```

**Comment by rbro** [comment]
Thanks for your help.  I was trying to track a performance issue and thought it was related to the above, but it might be something else as I am passing a format for each cell in my real code.  I'll create a new issue if I run into it again.

**Comment by johmue** [comment]
Keep in mind that creating a format on each iteration is an expensive operation. If possible you should create the format beforehand and pass it along.
