### ISSUE TITLE
New functions in LibXL 3.6.2

### ISSUE THREAD

**Issue by Jan-E** [iliaal/php_excel#129]
LibXL has 4 new functions. See http://libxl.com/download.html

added new methods:
 - Sheet::setAutoFitArea()
 - Sheet::printRepeatRows()
 - Sheet::printRepeatCols()
 - Sheet::printArea()

Is anybody working on implementing these functions in PHP_Excel?

**Comment by johmue** [comment]
Yes... most likely a PR will show up in the coming days.

**Comment by Jan-E** [comment]
OK, thanks.
