### ISSUE TITLE
Sheet name of multibyte characters

### ISSUE THREAD

**Issue by hiroshist** [iliaal/php_excel#133]
Hello,

I want to set the multibyte characters in the sheet name.
I can not be set more than 30 bytes to the sheet name be designated Excel2007 option.

Is this by design?

setlocale(LC_ALL, 'ja_JP.UTF-8');
$book = new ExcelBook(NULL,NULL,TRUE);
$book->addSheet('１２３４５６７８９０１２３４５６７８９０');

Thank you.

**Comment by iliaal** [comment]
Yes, that's the limitation of the libXL library.
