### ISSUE TITLE
writing cell starting with equals sign

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#134]
In Excel, if you need a cell to start with an equals sign that is not a formula, you can put a single quote before the text like: '==abc==

Excel hides the single quote and renders it as: ==abc==

Is there a way to do the same behavior in php_excel?  I tried the below, but neither worked.  The 1st cell renders as blank and the 2nd cell displays the single quote, which I was hoping to hide like Excel does.  Thanks for your help.

```
$libxl = new ExcelBook('', '', true);

$o_sheet = $libxl->addSheet('test');

$o_sheet->write(1, 0, "==abc==");
$o_sheet->write(1, 1, "'==abc==");

$libxl->save('temp.xlsx');
```

**Comment by segadora** [comment]
Try setting cell type to CELLTYPE_STRING

```
$sheet->cellType($row, ExcelSheet::CELLTYPE_STRING);
```

**Comment by cbroissa** [comment]
Hello
We have the same problem, any news ?

Thank you.

**Comment by johmue** [comment]
With the latest version it should be possible to force string behaviour by prefixing the string with a single quote ```'=3+4```
