### ISSUE TITLE
Formula with filepath

### ISSUE THREAD

**Issue by rvdsarr** [iliaal/php_excel#140]
Im trying to write this formula to a cell in a sheet.

$s->write($row = 4, $column = 4, "='\\\\server\data\files\\$year\\$monthext\[{$number_d}.xls]Sheet1'!\$F\$36", $format = null, ExcelFormat::AS_FORMULA);
It however does not write anything to that column. It's blank. This does work:

"=SUM(E{$startingrow}:E{$rowno2})"
If I remove the AS_FORMULA, it does put this in the cell:

='\\server\data\files\2015\6. Juni\[20150602.xls]Sheet1'!$F$36
Im not sure what im doing wrong here. Thanks for the support!

**Comment by iliaal** [comment]
I am guessing this an issue with libxl library as opposed to the extension, have you tried to reach out to the libxl author?
