### ISSUE TITLE
PHPExcel not working with PHP 7.0

### ISSUE THREAD

**Issue by Ajtak** [iliaal/php_excel#141]
Remove this item. Thank you.

**Comment by fischel** [comment]
I think you confuse PHPExcel with php_excel :-)

Try your question here:

https://phpexcel.codeplex.com/


Stephan

**Comment by iliaal** [comment]
Try the php7 branch it works with PHP 7

**Comment by swapnilb0506** [comment]
hi
Fatal error: 'break' not in the 'loop' or 'switch' context in
\PHPExcel\PHPExcel\Calculation\Functions.php on line 581

This  error come out for  when  download excel file open in excel 2007.

Please fix this problem . Thank you.

**Comment by johmue** [comment]
Hi @swapnilb0506 [PHPExcel](https://github.com/PHPOffice/PHPExcel) is a different project and was replaced by [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet)

This project compiles as PHP extension written in C while yours is a pure PHP implementation.
