### ISSUE TITLE
A way for changing the description / Author of the excel file

### ISSUE THREAD

**Issue by talyaseen** [iliaal/php_excel#145]
Hi,
We love what's been done here! thank you guys. 

We would love to see a way for changing the description + Author/company of the excel file (right-click -> get info/properties)
Thanks! Much appreciated.

**Comment by johmue** [comment]
I don't think this is possible with the libxl library. If you find an appropriate function in the [libxl documentation](http://libxl.com/workbook.html) we may be able to incorporate that but I haven't found something so far.
