### ISSUE TITLE
Can't ./configure the library under Mac OS X El Capitan (10.11.1)

### ISSUE THREAD

**Issue by talyaseen** [iliaal/php_excel#146]
I've tried everything. Copied the libxl.so to /usr/local/lib  + ran it under sudo.. disabled rootless feature within the mac os x el capitan.

The following is the result...
xxxx$ ./configure --with-libxl-incdir=/tmp/libxl/libxl-3.6.5.0/include_c --with-libxl-libdir=/tmp/liblx/libxl-3.6.5.0/lib64
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.0.0
checking host system type... x86_64-apple-darwin15.0.0
checking target system type... x86_64-apple-darwin15.0.0
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable excel support... yes, shared
checking C include dir for libxl... yes, shared
checking lib dir for libxl... yes, shared
checking libxml2 install dir... yes, shared
checking for excel includes... found in /tmp/libxl/libxl-3.6.5.0/include_c
checking for excel libraries... not found
configure: error: Please reinstall the excel distribution

I even tried --with-excel and --with-excel=<PATH_TO_LIBXL.SO>

Please assist, as we were only able to build it on our server and had to work on the server instead of local/test environment.

**Comment by johmue** [comment]
I'm not familiar with Mac but https://www.macports.org/ports.php?by=name&substr=Php_excel may be helpful for you

**Comment by ryandesign** [comment]
Sounds like you downloaded libxl for the wrong platform (Linux, for example). A lib64 directory is not used on OS X, nor is the .so library extension commonly used. Remove whatever parts of the Linux libxl you installed, then download libxl for Mac OS X and install it somewhere permanent (i.e. not in /tmp). Then you should be able to build php-excel against it. Or, as @johmue said, use my php-excel port in MacPorts, which does everything for you.

**Comment by jwestbrook** [comment]
If this helps here is my configure statement with the directory structure like this

/usr/local/src/libxl/libxl-mac-3.6.2.0
/usr/local/src/libxl/php_excel

I run `configure` in the php_excel directory

```
./configure --prefix=/usr/local --with-excel=../libxl-mac-3.6.2.0 --with-libdir=../libxl-mac-3.6.2.0/lib --with-libxl-incdir=../libxl-mac-3.6.2.0/include_c --with-libxl-libdir=../libxl-mac-3.6.2.0/lib
```

and everything compiles correctly

However I'm running into a problem that the compiled `excel.so` is using a relative path to point to the libxl.dylib file

I get this error when bouncing apache to load the extension
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-libxl/excel.so' - dlopen(/usr/local/opt/php56-libxl/excel.so, 9): Library not loaded: libxl.dylib\n  Referenced from: /usr/local/opt/php56-libxl/excel.so\n  Reason: unsafe use of relative rpath libxl.dylib in /usr/local/opt/php56-libxl/excel.so with restricted binary in Unknown on line 0
```

I've tried running the `install_name_tool` but it doesnt change the results :-(

command line php loads the extension and library just fine

FYI using homebrew php56

**Comment by sabutterworth** [comment]
It might seem obvious. But, did you try changing the relative paths for libxl to an absolute path: /usr/local/src/libxl/libxl-mac-3.6.2.0

**Comment by jwestbrook** [comment]
Yep I changed them back and forth with the same results. I think it has something to do with the actual compiling of the SO which is a little out of my realm of expertise.

**Comment by johmue** [comment]
Is it possible that you have two versions of library installed? Or Art least you should try with the latest libxl version...

**Comment by iliaal** [comment]
When specifying the lib/include dir always use explicit paths, also check with ldd that libxl library is usable.

**Comment by jwestbrook** [comment]
using this stackoverflow answer  http://stackoverflow.com/a/33300738 got me there

go to folder where `excel.so` is located

```
$ otool -L excel.so
excel.so:
	libxl.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$ mdfind libxl.dylib
/usr/local/src/libxl/libxl-mac-3.6.5.2/lib/libxl.dylib
$ cp /usr/local/src/libxl/libxl-mac-3.6.5.2/lib/libxl.dylib /usr/local/lib/
$ install_name_tool -change libxl.dylib /usr/local/lib/libxl.dylib excel.so
$ otool -L excel.so
excel.so:
	/usr/local/lib/libxl.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$ sudo apachectl restart
```
