### ISSUE TITLE
64-bit

### ISSUE THREAD

**Issue by davidsteinsland** [iliaal/php_excel#150]
You are searching for `libxl.so` in `$PHP_LIBDIR`. On my system this is `lib`, but since I'm running 64-bit CentOS, the path should be `lib64`.

I have my libxl distro installed in `/usr/include` and `/usr/lib64` and I would like that the configure script localizes these files by default (it finds the includes, but not the lib)

**Comment by iliaal** [comment]
You need to explicitly specify the lib dir via --with-libxl-libdir config directive
