### ISSUE TITLE
Decrypt XLS with password

### ISSUE THREAD

**Issue by alexromeo** [iliaal/php_excel#152]
Hi,

Can php_excel read XLS files which are protected by password? I have the corresponding password, obviously, I don't want to crack the file.

Thanks in advance and congrats on your work!

**Comment by johmue** [comment]
I don't think it is possible with libxl BUT if you're running Excel on the same machine you may be able to use the COM or DOTNET interface provided by PHP to decrypt the file with excel before using it with libxl. Unfortunately the documentation is poor for these interfaces.

**Comment by alexromeo** [comment]
Thanks!

**Comment by jaydadhania08** [comment]
I welcome you to check out my [PHPDecryptXLSXWithPassword](https://github.com/jaydadhania08/PHPDecryptXLSXWithPassword) repo. It can decrypt an XLSX file with given password and generate an unprotected (open) XLSX file. Then you can use it with PHPSpreadsheet.

**Comment by luisalonsobr** [comment]
> I welcome you to check out my [PHPDecryptXLSXWithPassword](https://github.com/jaydadhania08/PHPDecryptXLSXWithPassword) repo. It can decrypt an XLSX file with given password and generate an unprotected (open) XLSX file. Then you can use it with PHPSpreadsheet. Edit: it also works on DOCX and PPTX files.

God bless you
