### ISSUE TITLE
Issue with Named Ranges

### ISSUE THREAD

**Issue by DropdeadFredd** [iliaal/php_excel#156]
Hi

I'm having an issue with the setNamedRange function.

The PHP documentation says:

setNamedRange($name, $row_from, $column_from, $row_to, $column_to, $scope_id = null)

But when I call it with the following:

setNamedRange( 'ReportData', 1, 0, 2, 1 );

I get an error: "The range row start cannot be greater than row end."

If I call the function as:

setNamedRange($name, $row_from, $row_to, $column_from, $column_to, $scope_id = null)

It returns true but when I open the Workbook in Excel I get an error:

"Excel found unreadable content"

I've attached the excel log. 

I'm running on Windows 10:

PHP 5.5.26
LibXL 3.6.5.0
Excel 2007

The php_excel dll I have is from 06/06/2014, Product Version 5.5.11

Any ideas? I don't know if this is a php_excel issue or a problem with LibXL

Thanks, Fred

[error062480_01.txt](https://github.com/iliaal/php_excel/files/202367/error062480_01.txt)

**Comment by DropdeadFredd** [comment]
Hi

Forgot to mention, I'm testing with the trial version of LibXL.


Thanks again, Fred

**Comment by johmue** [comment]
@DropdeadFredd thanks for the info.

Whenever you experience this kind of error you can directly look into the c code - it's not much harder than reading php code. The ```zend_parse_parameters()``` function is the one which is responsible for parsing the parameters...

```c
#if LIBXL_VERSION >= 0x03010000
/* {{{ proto bool ExcelSheet::setNamedRange(string name, int row, int col, int to_row, int to_col [, int scope_id])
	Create a named range */
EXCEL_METHOD(Sheet, setNamedRange)
{
	SheetHandle sheet;
	zval *object = getThis();
	long row, to_row, col, to_col;
	char *name;
	int name_len;
#if LIBXL_VERSION >= 0x03050401
	long scope_id = SCOPE_WORKBOOK;

	if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "sllll|l", &name, &name_len, &row, &to_row, &col, &to_col, &scope_id) == FAILURE) {
#else
	if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "sllll", &name, &name_len, &row, &to_row, &col, &to_col) == FAILURE) {
#endif
		RETURN_FALSE;
	}

	if (!name_len) {
		php_error_docref(NULL TSRMLS_CC, E_WARNING, "The range name cannot be empty.");
		RETURN_FALSE;
	}
	if (row > to_row) {
		php_error_docref(NULL TSRMLS_CC, E_WARNING, "The range row start cannot be greater than row end.");
		RETURN_FALSE;
	} else if (col > to_col) {
		php_error_docref(NULL TSRMLS_CC, E_WARNING, "The range column start cannot be greater than column end.");
		RETURN_FALSE;
	}

	SHEET_FROM_OBJECT(sheet, object);

#if LIBXL_VERSION >= 0x03050401
	RETURN_BOOL(xlSheetSetNamedRange(sheet, name, row, to_row, col, to_col, scope_id));
#else
	RETURN_BOOL(xlSheetSetNamedRange(sheet, name, row, to_row, col, to_col));
#endif
}
/* }}} */
```
