### ISSUE TITLE
Fatel Error reading excel file

### ISSUE THREAD

**Issue by kallaad** [iliaal/php_excel#159]
Hi,

I have successfully installed libxl and php_excel on my server. Please check phpinfo.zip attached.

I am able to write the excel file without any problem. But when I try to read the file I have got some error.

[phpinfo().zip](https://github.com/iliaal/php_excel/files/218435/phpinfo.zip)

```
$libxl = new ExcelBook('', '', true);
$libxl->loadFile('excel.xlsx');
$worksheet = $libxl->getSheet();

$row = 1;

while ($row < $worksheet->lastRow())
{
    if ($worksheet->readRow($row) === false)
    {
        echo 'false';
        exit;
    }

    $row++;
}
```

[Error]
PHP Fatal error:  Uncaught Error: Call to a member function lastRow() on boolean

Please help

**Comment by johmue** [comment]
try
```php
$libxl->loadFile(realpath('excel.xlsx'));
```

**Comment by kallaad** [comment]
Hi,

I have tried, but getting the same error again.
PHP Fatal error:  Uncaught Error: Call to a member function readRow() on boolean

Kindly Note: I am getting the error only for .XLSX files

**Comment by kallaad** [comment]
Hi, Would you have any update for me. I tried using either  
$libxl->loadFile('excel.xls'); or
$libxl->loadFile(realpath('excel.xls'));
and it works fine for *.xls files. 
However, I get "PHP Fatal error: Uncaught Error: Call to a member function readRow() on boolean" by using any of the above mentioned functions with only *.xlsx files

**Comment by johmue** [comment]
Unfortunately no. But have you checked that It is really an *.xlsx file. It will not work if you try to open an *.xlsx file which is just renamed from *.xls to *.xlsx. According to the format of the workbook you also need to asure the correct parameter for the ```new ExcelBook(null, null, <format>)```.

An have you checked if this is the case for *.xlsx files in general or just for the one you have tried.

**Comment by iliaal** [comment]
Can you please provide the excel file in question?

**Comment by kallaad** [comment]
Hi,
Please check the attached file.

[phpexcel.zip](https://github.com/iliaal/php_excel/files/329243/phpexcel.zip)

**Comment by iliaal** [comment]
With the latest PHP7 branch this works fine.

**Comment by vinmark016** [comment]
I am experiencing this error.
