### ISSUE TITLE
How to define a text printed on every page

### ISSUE THREAD

**Issue by webshaker** [iliaal/php_excel#162]
Hi

I'd like to put a text on the top of each printed page of the Excel file.
There is a function called

setHeader

But it not seem's to take any parameters !

thank's

**Comment by webshaker** [comment]
Sorry forget my question

setHeader work's
it took 2 parameters
a string and the margin.

**Comment by johmue** [comment]
btw - just in case: there are some special codes that can be used in setHeader() and setFooter() e.g for sheet name etc. see here for a complete list http://libxl.com/spreadsheet.html?lang=c#setHeader

**Comment by webshaker** [comment]
thank's for the doc.
