### ISSUE TITLE
Any idea how to build it for Windows x64?

### ISSUE THREAD

**Issue by quantuumsnot** [iliaal/php_excel#164]
?

**Comment by johmue** [comment]
Hi,

You can either grab pre-compiled dlls here https://www.apachelounge.com/viewtopic.php?t=6617 or if you really like to build it on your own you can have a look at https://github.com/johmue/win-php-sdk-builder - i'd recommend using the pre-compiled dll in a fresh copy of php from http://windows.php.net

**Comment by Jan-E** [comment]
> You can either grab pre-compiled dlls here https://www.apachelounge.com/viewtopic.php?t=6617

Or here: https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by quantuumsnot** [comment]
Thanks, downloaded 7.1.0a3
