### ISSUE TITLE
Error xml_utf8_decode after install

### ISSUE THREAD

**Issue by Decadence** [iliaal/php_excel#165]
Hi, I am having trouble with the installation, could you help me?
When I try to load extension I get the error:

```PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/excel.so' - /usr/lib64/php/modules/excel.so: undefined symbol: xml_utf8_decode in Unknown on line 0```

I'm using libxl-lin-3.6.5 and PHP Excel 1.0.2 for PHP5 from here https://github.com/iliaal/php_excel/releases/download/Excel-1.0.2-PHP5/excel-1.0.2-php5.tgz .

Here is how to install:

[root@delme excel-1.0.2]# phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
[root@delme excel-1.0.2]# ./configure --with-libxl-incdir=../libxl-3.6.5.0/include_c --with-libxl-libdir=../libxl-3.6.5.0/lib64 --with-excel=../libxl-3.6.5.0/ --with-libxml-dir=/usr/include/libxml2/
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking whether to enable excel support... yes, shared
checking C include dir for libxl... yes, shared
checking lib dir for libxl... yes, shared
checking libxml2 install dir... yes, shared
checking for excel includes... found in ../libxl-3.6.5.0/include_c
checking for excel libraries... found in ../libxl-3.6.5.0/lib64
checking for libxml2... found in /usr/include/libxml2/
checking for xlCreateBookCA in -lxl... yes
checking for xlBookSetKeyA in -lxl... yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
[root@delme excel-1.0.2]# make
/bin/sh /root/excel-1.0.2/libtool --mode=compile cc  -I. -I/root/excel-1.0.2 -DPHP_ATOM_INC -I/root/excel-1.0.2/include -I/root/excel-1.0.2/main -I/root/excel-1.0.2 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/libxl-3.6.5.0/include_c -I/usr/include/libxml2/  -DHAVE_CONFIG_H  -g -O2   -c /root/excel-1.0.2/excel.c -o excel.lo
libtool: compile:  cc -I. -I/root/excel-1.0.2 -DPHP_ATOM_INC -I/root/excel-1.0.2/include -I/root/excel-1.0.2/main -I/root/excel-1.0.2 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/libxl-3.6.5.0/include_c -I/usr/include/libxml2/ -DHAVE_CONFIG_H -g -O2 -c /root/excel-1.0.2/excel.c  -fPIC -DPIC -o .libs/excel.o
/bin/sh /root/excel-1.0.2/libtool --mode=link cc -DPHP_ATOM_INC -I/root/excel-1.0.2/include -I/root/excel-1.0.2/main -I/root/excel-1.0.2 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/libxl-3.6.5.0/include_c -I/usr/include/libxml2/  -DHAVE_CONFIG_H  -g -O2   -o excel.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/excel-1.0.2/modules  excel.lo -Wl,-rpath,/root/libxl-3.6.5.0/lib64 -L/root/libxl-3.6.5.0/lib64 -lxl -Wl,-rpath,/root/libxl-3.6.5.0/lib64 -L/root/libxl-3.6.5.0/lib64 -lxl
libtool: link: cc -shared  .libs/excel.o   -L/root/libxl-3.6.5.0/lib64 -lxl  -Wl,-rpath -Wl,/root/libxl-3.6.5.0/lib64 -Wl,-rpath -Wl,/root/libxl-3.6.5.0/lib64   -Wl,-soname -Wl,excel.so -o .libs/excel.so
libtool: link: ( cd ".libs" && rm -f "excel.la" && ln -s "../excel.la" "excel.la" )
/bin/sh /root/excel-1.0.2/libtool --mode=install cp ./excel.la /root/excel-1.0.2/modules
libtool: install: cp ./.libs/excel.so /root/excel-1.0.2/modules/excel.so
libtool: install: cp ./.libs/excel.lai /root/excel-1.0.2/modules/excel.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin:/sbin" ldconfig -n /root/excel-1.0.2/modules

Libraries have been installed in:
   /root/excel-1.0.2/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.

Build complete.
Don't forget to run 'make test'.

[root@delme excel-1.0.2]# make install
Installing shared extensions:     /usr/lib64/php/modules/

Later I added extension to php.ini and following error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/excel.so' - /usr/lib64/php/modules/excel.so: undefined symbol: xml_utf8_decode in Unknown on line 0
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mhash
openssl
pcntl
pcre
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

```
My environment:

OS:
CentOS release 6.8 (Final)
Linux 2.6.32-37-pve #1 SMP Wed Mar 18 08:19:56 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
GCC:
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
XML version:
2.7.6
```

Php installed from Remi repo:
php-cli.x86_64                  5.6.23-1.el6.remi                @remi-php56    
php-common.x86_64               5.6.23-1.el6.remi                @remi-php56    
php-devel.x86_64                5.6.23-1.el6.remi                @remi-php56    
php-pecl-jsonc.x86_64           1.3.10-1.el6.remi.5.6            @remi-php56    
php-pecl-jsonc-devel.x86_64     1.3.10-1.el6.remi.5.6            @remi-php56    
php-pecl-zip.x86_64             1.13.3-1.el6.remi.5.6            @remi-php56    
php-xml.x86_64                  5.6.23-1.el6.remi                @remi-php56

Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib]
  --ldflags           []
  --libs              [-lcrypt   -lcrypt -ledit -lncurses -lstdc++ -lz -lrt -lm -ldl -lnsl  -lxml2 -lz -lm -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lcrypt -lcrypt ]
  --extension-dir     [/usr/lib64/php/modules]
  --include-dir       [/usr/include/php]
  --man-dir           [/usr/share/man]
  --php-binary        [/usr/bin/php]
  --php-sapis         [apache2handler embed fpm  cli phpdbg cgi]
  --configure-options [--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --target=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --cache-file=../config.cache --with-libdir=lib64 --with-config-file-path=/etc --with-config-file-scan-dir=/etc/php.d --disable-debug --with-pic --disable-rpath --without-pear --with-exec-dir=/usr/bin --with-freetype-dir=/usr --with-png-dir=/usr --with-xpm-dir=/usr --enable-gd-native-ttf --with-t1lib=/usr --without-gdbm --with-jpeg-dir=/usr --with-openssl --with-system-ciphers --with-zlib --with-layout=GNU --with-kerberos --with-libxml-dir=/usr --with-system-tzdata --with-mhash --enable-dtrace --libdir=/usr/lib64/php --enable-pcntl --enable-opcache --enable-phpdbg --with-imap=shared --with-imap-ssl --enable-mbstring=shared --enable-mbregex --with-gd=shared,/usr --with-gmp=shared --enable-calendar=shared --enable-bcmath=shared --with-bz2=shared --enable-ctype=shared --enable-dba=shared --with-db4=/usr --with-gdbm=/usr --with-tcadb=/usr --enable-exif=shared --enable-ftp=shared --with-gettext=shared --with-iconv=shared --enable-sockets=shared --enable-tokenizer=shared --with-xmlrpc=shared --with-ldap=shared --with-ldap-sasl --enable-mysqlnd=shared --with-mysql=shared,mysqlnd --with-mysqli=shared,mysqlnd --with-mysql-sock=/var/lib/mysql/mysql.sock --with-oci8=shared,instantclient,/usr/lib64/oracle/12.1/client64/lib,12.1 --with-pdo-oci=shared,instantclient,/usr,12.1 --with-interbase=shared,/usr/lib64/firebird --with-pdo-firebird=shared,/usr/lib64/firebird --enable-dom=shared --with-pgsql=shared --enable-simplexml=shared --enable-xml=shared --enable-wddx=shared --with-snmp=shared,/usr --enable-soap=shared --with-xsl=shared,/usr --enable-xmlreader=shared --enable-xmlwriter=shared --with-curl=shared,/usr --enable-pdo=shared --with-pdo-odbc=shared,unixODBC,/usr --with-pdo-mysql=shared,mysqlnd --with-pdo-pgsql=shared,/usr --with-pdo-sqlite=shared,/usr --with-pdo-dblib=shared,/usr --with-sqlite3=shared,/usr --without-readline --with-libedit --with-pspell=shared --enable-phar=shared --with-mcrypt=shared,/usr --with-tidy=shared,/usr --with-mssql=shared,/usr --with-sybase-ct=shared,/usr --enable-sysvmsg=shared --enable-sysvshm=shared --enable-sysvsem=shared --enable-shmop=shared --enable-posix=shared --with-unixODBC=shared,/usr --enable-fileinfo=shared --enable-intl=shared --with-icu-dir=/usr --with-enchant=shared,/usr --with-recode=shared,/usr build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu target_alias=x86_64-redhat-linux-gnu CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing -Wno-pointer-sign CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic]
  --version           [5.6.23]
  --vernum            [50623]

**Comment by iliaal** [comment]
The problem is that the xml_utf8_decode function is inside the xml extension that was compiled as a shared extension and is being loaded AFTER excel.so

Try changing the order in which extensions are being loaded so that xml.so is loaded before excel.so

**Comment by Decadence** [comment]
@iliaal Thanks! You're right, this is exactly what I needed to do.
