### ISSUE TITLE
Dropdown values are missing after saving xlsm file

### ISSUE THREAD

**Issue by Decadence** [iliaal/php_excel#167]
Hello. 
I'm using LibXL and your extension and I have one problem.
When I edit Excel book which contains dropdown cells and save it (I don't even touch these cells) new file hasn't that dropdown values, just empty cell. Is there any way to handle this and save dropdowns?

![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/17142662/9f0224b4-5359-11e6-8aaa-3cae834f6c94.png)

**Comment by iliaal** [comment]
I am pretty sure you may have come across a limitation of the libxl library. You can try reading the cell in the extension and writing it back, maybe that will preserve the formatting?

**Comment by Decadence** [comment]
What limitation are you talking about? I have LibXL license if it matters.

I'll try to be more detailed: I have excel file that contains cells which possible values are restricted by some range of options. When I open this book and save (without any modification of these cells), these options are disappeared. It's not about formatting, it's about preserving cell options.
If I write value to this cell, it's saved but restriction disappears. I want to user can select option after he opens generated file.

On screenshot I show where these options are configured. After save configuration resets.

Sorry, I don't have english version of MS Excel.

![screenshot_2](https://cloud.githubusercontent.com/assets/1434668/17143416/dce9495e-535b-11e6-981d-48d8b67bd7ed.png)

**Comment by Decadence** [comment]
@iliaal are you here?

**Comment by Decadence** [comment]
Ok, I found possible reason.
It only happens when cell and options range are on the different sheets.
Here is sample file
[dropdown_list.xlsx](https://github.com/iliaal/php_excel/files/386148/dropdown_list.xlsx)
Do you have any thoughts how to fix it?

**Comment by iliaal** [comment]
As I stated earlier, this is an issue with the libxl library itself, not the PHP extension, since all the back-end work involved in reading/writing data is done by the library, PHP extension only wraps the internal C interface. Have you tried filing an issue on the bug tracker of libxl?

**Comment by Decadence** [comment]
@iliaal Ok, where can I find this bug tracker? Or you mean support@libxl.com? I contacted via this email, with no solution for now.

**Comment by iliaal** [comment]
Yes, I am referring to the support e-mail address, I usually find that Dmytro is very responsive.

**Comment by Decadence** [comment]
@iliaal Thanks for help, I will continue with LibXL support.

**Comment by Jan-E** [comment]
> Here is sample file
> https://github.com/iliaal/php_excel/files/386148/dropdown_list.xlsx

@Decadence If I open that file in my Excel 2010 and save it unmodified, the dropdownlist remains as it was. Did you try to create and save the dropdownlist without the use of LibXL?

**Comment by Decadence** [comment]
Yes I did.
Excel works fine.
I created that file in Excel 2010. While you're working in Excel it saves ok. If you open and save it with LibXL, options are not linked to cell.

**Comment by Decadence** [comment]
If options and cell are on the same sheet, it seems work fine. If they are on different sheets, it doesn't.

**Comment by johmue** [comment]
Sounds like a bug in the libxl library. Please contact support@libxl.com

**Comment by Decadence** [comment]
Thanks, I've done it already.
