### ISSUE TITLE
Cannot mock ExcelSheet with PHPUnit

### ISSUE THREAD

**Issue by Platzengys** [iliaal/php_excel#168]
Hi,

I've encountered the problem when trying to mock ExcelSheet class with PHPUnit (version 4.8.26).
Error message says: `PHP Fatal error:  Redefinition of parameter $col_s in /var/www/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290) : eval()'d code on line 693`.

This error is thrown when method has duplicated parameters. I'm not sure, but I think problem can be [right here](https://github.com/iliaal/php_excel/blob/Excel-1.0.2-PHP7/excel.c#L5012).

I'm using PHP 7.0.10-2+deb.sury.org~trusty+1 on Ubuntu 14.04.5 LTS, PHP Excel 1.0.2 for PHP7 and libxl version is 3.6.5

It'd be very useful if someone could identify and fix this bug.

**Comment by iliaal** [comment]
Resolved with latest patch
