### ISSUE TITLE
Php excel on Centos 7 not working.

### ISSUE THREAD

**Issue by MatteoMrx8** [iliaal/php_excel#172]
Hi all,
  i've tried to install php excel on Centos 7 64 bit with no lucky.
I've tried it on three different machines (Centos7 development machine, Cento7 fresh installed machine, OSX El Capitan).
I've also tried with mac ports and extension was installed correctly and working, so i'm sure it can be done in some way.
I'll report only last experience on fresh installed Os.
After having installa Developer tools i've done this steps:

git clone https://github.com/iliaal/php_excel.git ext/excel
Cloning into 'ext/excel'...
remote: Counting objects: 1087, done.
remote: Total 1087 (delta 0), reused 0 (delta 0), pack-reused 1087
Ricezione degli oggetti: 100% (1087/1087), 589.98 KiB | 704.00 KiB/s, done.
Risoluzione dei delta: 100% (680/680), done.
[root@25130 ~]# ls -ltra
totale 36
-rw-r--r--  1 root root  129 29 dic  2013 .tcshrc
-rw-r--r--  1 root root  100 29 dic  2013 .cshrc
-rw-r--r--  1 root root  176 29 dic  2013 .bashrc
-rw-r--r--  1 root root  176 29 dic  2013 .bash_profile
-rw-r--r--  1 root root   18 29 dic  2013 .bash_logout
drwxr-xr-x 19 root root 4096 13 set 18.52 ..
drwxr-----  3 root root 4096 14 set 17.35 .pki
dr-xr-x---  4 root root 4096 14 set 17.48 .
drwxr-xr-x  3 root root 4096 14 set 17.48 ext

[root@25130 ~]#wget http://www.libxl.com/download/libxl-lin-3.6.5.tar.gz
[root@25130 ~]# gunzip libxl-lin-3.6.5.tar.gz
[root@25130 ~]# tar xvf libxl-lin-3.6.5.tar

[root@25130 ~]# cd ext/
[root@25130 ext]# cd excel/

[root@25130 excel]# ./configure --with-excel=../libxl-3.6.5.0/ --with-libxl-libdir=../libxl-3.6.5.0/lib64/ --with-libxl-incdir=../libxl-3.6.5.0/include_c
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable excel support... yes, shared
checking C include dir for libxl... yes, shared
checking lib dir for libxl... yes, shared
checking libxml2 install dir... yes, shared
checking for excel includes... found in ../libxl-3.6.5.0/include_c
checking for excel libraries... found in ../libxl-3.6.5.0/lib64/
checking for libxml2... not found
checking for xlCreateBookCA in -lxl... yes
checking for xlBookSetKeyA in -lxl... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
[root@25130 excel]# make
/bin/sh /root/ext/excel/libtool --mode=compile cc  -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c  -DHAVE_CONFIG_H  -g -O2   -c /root/ext/excel/excel.c -o excel.lo 
libtool: compile:  cc -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c -DHAVE_CONFIG_H -g -O2 -c /root/ext/excel/excel.c  -fPIC -DPIC -o .libs/excel.o
In file included from /usr/include/php/ext/xml/php_xml.h:35:0,
                 from /root/ext/excel/excel.c:32:
/usr/include/php/ext/xml/expat_compat.h:36:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
make: **\* [excel.lo] Errore 1

Then i've installed libxml wich seems to miss.
### yum install libxml2-devel

Risoluzione dipendenze
--> Esecuzione del controllo di transazione
---> Pacchetto libxml2-devel.x86_64 0:2.9.1-6.el7_2.3 settato per essere installato
--> Elaborazione dipendenza: zlib-devel per il pacchetto: libxml2-devel-2.9.1-6.el7_2.3.x86_64
--> Elaborazione dipendenza: xz-devel per il pacchetto: libxml2-devel-2.9.1-6.el7_2.3.x86_64
--> Esecuzione del controllo di transazione
---> Pacchetto xz-devel.x86_64 0:5.1.2-12alpha.el7 settato per essere installato
---> Pacchetto zlib-devel.x86_64 0:1.2.7-15.el7 settato per essere installato
--> Risoluzione delle dipendenze completata

Dipendenze risolte
# 
#  Package                                           Arch                                       Versione                                                 Repository                                   Dim.

Installazione:
 libxml2-devel                                     x86_64                                     2.9.1-6.el7_2.3                                          updates                                     1.0 M
Installazioni per dipendenze:
 xz-devel                                          x86_64                                     5.1.2-12alpha.el7                                        base                                         44 k
 zlib-devel                                        x86_64                                     1.2.7-15.el7                                             base                                         50 k
# Riepilogo della transazione

Install  1 Pacchetto (+2 Pacchetti dipendenti)

Dimensione totale del download: 1.1 M
Dimensione installata: 9.1 M
Is this ok [y/d/N]: y
Downloading packages:
(1/3): zlib-devel-1.2.7-15.el7.x86_64.rpm                                                                                                                                         |  50 kB  00:00:00  
(2/3): xz-devel-5.1.2-12alpha.el7.x86_64.rpm                                                                                                                                      |  44 kB  00:00:00     
## (3/3): libxml2-devel-2.9.1-6.el7_2.3.x86_64.rpm                                                                                                                                   | 1.0 MB  00:00:00     

Totale                                                                                                                                                                   6.0 MB/s | 1.1 MB  00:00:00  
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installazione     : xz-devel-5.1.2-12alpha.el7.x86_64                                                                                                                                              1/3 
  Installazione     : zlib-devel-1.2.7-15.el7.x86_64                                                                                                                                                 2/3 
  Installazione     : libxml2-devel-2.9.1-6.el7_2.3.x86_64                                                                                                                                           3/3 
  Verifica in corso : zlib-devel-1.2.7-15.el7.x86_64                                                                                                                                                 1/3 
  Verifica in corso : xz-devel-5.1.2-12alpha.el7.x86_64                                                                                                                                              2/3 
  Verifica in corso : libxml2-devel-2.9.1-6.el7_2.3.x86_64                                                                                                                                           3/3 

Installato:
  libxml2-devel.x86_64 0:2.9.1-6.el7_2.3                                                                                                                                                                 

Dipendenza installata:
  xz-devel.x86_64 0:5.1.2-12alpha.el7                                                                  zlib-devel.x86_64 0:1.2.7-15.el7                                                                 

Completo!

Then installed re2c..
[root@25130 excel]# yum install re2c
Risoluzione dipendenze
--> Esecuzione del controllo di transazione
---> Pacchetto re2c.x86_64 0:0.14.3-2.el7 settato per essere installato
--> Risoluzione delle dipendenze completata

Dipendenze risolte
# 
#  Package                                       Arch                                            Versione                                              Repository                                     Dim.

Installazione:
 re2c                                          x86_64                                          0.14.3-2.el7                                          epel                                          230 k
# Riepilogo della transazione

Install  1 Pacchetto

Dimensione totale: 230 k
Dimensione installata: 677 k
Is this ok [y/d/N]: y
Downloading packages:
avvertimento: /var/cache/yum/x86_64/7/epel/packages/re2c-0.14.3-2.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, ID chiave 352c64e5: NOKEY
Recupero chiave da file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Importazione della chiave GPG 0x352C64E5:
 Userid     : "Fedora EPEL (7) epel@fedoraproject.org"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Pacchetto  : epel-release-7-8.noarch (installed)
 Da         : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Procedere [s/N]: s
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installazione     : re2c-0.14.3-2.el7.x86_64                                                                                                                                                       1/1 
  Verifica in corso : re2c-0.14.3-2.el7.x86_64                                                                                                                                                       1/1 

Installato:
  re2c.x86_64 0:0.14.3-2.el7                                                                                                                                                                             

Completo!

**Then it compiles correct**

[root@25130 excel]# ./configure --with-excel=../libxl-3.6.5.0/ --with-libxl-libdir=../libxl-3.6.5.0/lib64/ --with-libxl-incdir=../libxl-3.6.5.0/include_c --with-libxml-dir=/usr/include/libxml2/
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking whether to enable excel support... yes, shared
checking C include dir for libxl... yes, shared
checking lib dir for libxl... yes, shared
checking libxml2 install dir... yes, shared
checking for excel includes... found in ../libxl-3.6.5.0/include_c
checking for excel libraries... found in ../libxl-3.6.5.0/lib64/
checking for libxml2... found in /usr/include/libxml2/
checking for xlCreateBookCA in -lxl... yes
checking for xlBookSetKeyA in -lxl... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# 
[root@25130 excel]# make
/bin/sh /root/ext/excel/libtool --mode=compile cc  -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c -I/usr/include/libxml2/  -DHAVE_CONFIG_H  -g -O2   -c /root/ext/excel/excel.c -o excel.lo 
libtool: compile:  cc -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c -I/usr/include/libxml2/ -DHAVE_CONFIG_H -g -O2 -c /root/ext/excel/excel.c  -fPIC -DPIC -o .libs/excel.o
/bin/sh /root/ext/excel/libtool --mode=link cc -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c -I/usr/include/libxml2/  -DHAVE_CONFIG_H  -g -O2   -o excel.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/ext/excel/modules  excel.lo -Wl,-rpath,/root/ext/libxl-3.6.5.0/lib64 -L/root/ext/libxl-3.6.5.0/lib64 -lxl -Wl,-rpath,/root/ext/libxl-3.6.5.0/lib64 -L/root/ext/libxl-3.6.5.0/lib64 -lxl
libtool: link: cc -shared  -fPIC -DPIC  .libs/excel.o   -L/root/ext/libxl-3.6.5.0/lib64 -lxl  -O2 -Wl,-rpath -Wl,/root/ext/libxl-3.6.5.0/lib64 -Wl,-rpath -Wl,/root/ext/libxl-3.6.5.0/lib64   -Wl,-soname -Wl,excel.so -o .libs/excel.so
libtool: link: ( cd ".libs" && rm -f "excel.la" && ln -s "../excel.la" "excel.la" )
/bin/sh /root/ext/excel/libtool --mode=install cp ./excel.la /root/ext/excel/modules
libtool: install: cp ./.libs/excel.so /root/ext/excel/modules/excel.so
libtool: install: cp ./.libs/excel.lai /root/ext/excel/modules/excel.la
## libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/sbin" ldconfig -n /root/ext/excel/modules

Libraries have been installed in:
   /root/ext/excel/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
- add LIBDIR to the `LD_LIBRARY_PATH' environment variable
   during execution
- add LIBDIR to the `LD_RUN_PATH' environment variable
   during linking
- use the `-Wl,-rpath -Wl,LIBDIR' linker flag
- have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
## more information, such as the ld(1) and ld.so(8) manual pages.

Build complete.
Don't forget to run 'make test'.

[root@25130 excel]# make install
Installing shared extensions:     /usr/lib64/php/modules/

But as soon as i try to use it:

php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/excel.so' - /usr/lib64/php/modules/excel.so: undefined symbol: xml_utf8_decode in Unknown on line 0
[PHP Modules]

On both Centos and also on OSX when compiled by hand.
What did i miss?

**Comment by johmue** [comment]
Try to compile without libxml support. It's not needed if your credentials lack UTF8 characters.

**Comment by Nosforever** [comment]
Hi johmue, 
 already done. But it's not possible to compile without XML support.

[root@25130 excel]# ./configure --with-excel=../libxl-3.6.5.0/ --with-libxl-libdir=../libxl-3.6.5.0/lib64/ --with-libxl-incdir=../libxl-3.6.5.0/include_c
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking whether to enable excel support... yes, shared
checking C include dir for libxl... yes, shared
checking lib dir for libxl... yes, shared
checking libxml2 install dir... yes, shared
checking for excel includes... found in ../libxl-3.6.5.0/include_c
checking for excel libraries... found in ../libxl-3.6.5.0/lib64/
checking for libxml2... not found
checking for xlCreateBookCA in -lxl... yes
checking for xlBookSetKeyA in -lxl... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
[root@25130 excel]# make
/bin/sh /root/ext/excel/libtool --mode=install cp ./excel.la /root/ext/excel/modules
libtool: install: cp ./.libs/excel.so /root/ext/excel/modules/excel.so
libtool: install: cp ./.libs/excel.lai /root/ext/excel/modules/excel.la
libtool: finish: PATH="/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin" ldconfig -n /root/ext/excel/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /root/ext/excel/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

[root@25130 excel]# make clean
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f 
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
[root@25130 excel]# make
/bin/sh /root/ext/excel/libtool --mode=compile cc  -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c  -DHAVE_CONFIG_H  -g -O2   -c /root/ext/excel/excel.c -o excel.lo 
libtool: compile:  cc -I. -I/root/ext/excel -DPHP_ATOM_INC -I/root/ext/excel/include -I/root/ext/excel/main -I/root/ext/excel -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/ext/libxl-3.6.5.0/include_c -DHAVE_CONFIG_H -g -O2 -c /root/ext/excel/excel.c  -fPIC -DPIC -o .libs/excel.o
In file included from /usr/include/php/ext/xml/php_xml.h:35:0,
                 from /root/ext/excel/excel.c:32:
/usr/include/php/ext/xml/expat_compat.h:36:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
make: *** [excel.lo] Errore 1

**Comment by zemartino** [comment]
Experiencing the exact same problem with CentOS 7. Would love to compile it without libxml support, but this seems to be impossible. Any ideas?

**Comment by zemartino** [comment]
Found a quick and dirty fix to get things going:

Modify excel.c and remove the XML relevant parts, then compile again.

**Comment by ysumadwang** [comment]
cd /usr/include
ln -s libxml2/libxml  libxml
please try.

**Comment by RADiActive** [comment]
i fixed it with rename /etc/php.d/xml.ini to /etc/php.d/axml.ini

**Comment by Jan-E** [comment]
On CentOS6 I had the same problem. Solved by including a directory in CFLAGS and CPPFLAGS, so parser.h can be found:
```
# ls -la /usr/local/include/libxml2/libxml/parser.h
-rw-r--r-- 1 root root 39717 May 26  2016 /usr/local/include/libxml2/libxml/parser.h
```
Include /usr/local/include/libxml2:
```
export CFLAGS=-I/usr/local/include/libxml2
export CPPFLAGS=-I/usr/local/include/libxml2
./configure --with-excel=../libxl-3.8.0.4/ --with-libxl-libdir=../libxl-3.8.0.4/lib64 --with-libxl-incdir=../libxl-3.8.0.4/include_c --with-libxml-dir=/usr/local/lib
```
