### ISSUE TITLE
Excel-1.0.2-PHP5 branch ignores commercial license

### ISSUE THREAD

**Issue by demofly** [iliaal/php_excel#174]
CentOS 6, PHP 5.6.26 @remi
/etc/php.d/99-excel.ini:

```
extension=excel.so
[excel]
excel.license_name="BLA BLA"
excel.license_key="bla-bla"
excel.skip_empty=0
```

console check:

```
# php -i | grep -i excel
/etc/php.d/99-excel.ini,
excel
excel support => enabled
Excel Version => 1.0.2dev
```

And, trial banner is shown: http://pix.my/tAJqxbxL

Also, we have tested it with the newest libXL 3.7.0.1 with a commercial license, which re-updated today too.

**Comment by demofly** [comment]
Master branch has not this bug.

**Comment by belgattitude** [comment]
Yes this bug was fixed in master few days after releasing 1.0.2, see bug  #163 

Master looks well for me, I suppose @iliaal is gonna make a release soon. Maybe after testing with latest libxl (3.7.0). Let's see what happen, but I think this issue justifies an updated version.

**Comment by Gerst20051** [comment]
@belgattitude any idea who to ask so that we can get an updated version?

**Comment by Gerst20051** [comment]
Current Version Released Here https://github.com/Gerst20051/php_excel/releases/tag/Excel-1.0.2.1-PHP5

**Comment by belgattitude** [comment]
Hi @Gerst20051 ,

No reason I'm aware of, but master looks fine for me. Repo is quite stable

**Comment by cjsfj** [comment]
@Gerst20051 Are you able to release a php 7 version of this fix or a gist on how you did it? My efforts to deploy myself have not produced the expected outcome.

**Comment by Jan-E** [comment]
The git-head version is in my builds:
https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by cjsfj** [comment]
thanks @Jan-E , but my version is Linux.

**Comment by johmue** [comment]
For PHP 7 please use the php7 branch. The master branch is not compatible with PHP 7.
