### ISSUE TITLE
New libxl version 3.7.0 [feature_request]

### ISSUE THREAD

**Issue by selivan** [iliaal/php_excel#175]
New libxl version 3.7.0 http://www.libxl.com/changelog.html comes with plenty of new functions. Would be nice to add their support to php_excel

**Comment by johmue** [comment]
Please see #177 ... works with libxl >= 3.7.0.2

**Comment by selivan** [comment]
I still didn't test new libxl, because old one works just fine for us,, but I think this issue should be closed: support for new functions was added and merged into relevant branch.
