### ISSUE TITLE
cloning font object in php 7

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#176]
I'm getting an error running the below script in PHP 7.  It runs cleanly in PHP 5.6.

```
<?php
$libxl = new \ExcelBook;

$font = $libxl->addFont();

$format = $libxl->addFormat();
$format->setFont($font);

$new_font = clone $format->getFont();
```

The error is:

```
Fatal error: Uncaught Error: Trying to clone an uncloneable object of class ExcelFont in /tmp/excel.php:9
```

Should you be able to clone the font object like this in PHP 7?  Thanks for your help.

**Comment by johmue** [comment]
There is a bug in the c code in ```Fomat::getFont()``` method.

```c
// ...
ZVAL_OBJ(return_value, excel_object_new_sheet(excel_ce_font));
//                                      ^^^^^
fo = Z_EXCEL_FONT_OBJ_P(return_value);
// ...
```

It should be obviously ```[..]_new_font(excel_ce_font));```

I'll prepare a PR for this.
