### ISSUE TITLE
sheets don't keep references to books which is a segfault trap

### ISSUE THREAD

**Issue by pilif** [iliaal/php_excel#180]
`ExcelSheet` doesn't keep track of the parent `ExcelBook` which leads to a very simple situation where you can cause a segfault from user-space by calling a C++ method on a freed book object.

Here's a simple sample script with accompanying crash:

```shell
crazyhat@app99:~$ /opt/php/7.0/bin/php crash.php
pure virtual method called
terminate called without an active exception
Aborted
crazyhat@app99:~$
```

```php
<?php

$fname = 'crash.xlsx';

class Wrapper {
    private $book;

    function __construct($fname){
        $xlsfile = new ExcelBook('', '', true);
        $xlsfile->loadFile($fname);
        $xlsfile->setLocale('UTF-8');
        $this->book = $xlsfile;
    }

    function getFirstSheet(){
        return $this->book->getSheet(0);
    }
}

$sheet = (new Wrapper($fname))->getFirstSheet();
var_dump($sheet->firstRow());
```

Also, for convenience in cases like this it would also be great if `ExcelSheet` had a `getBook()` method to get to the parent book - as php_excel would need to keep track of that anyways, it probably makes sense to expose it too.

**Comment by johmue** [comment]
If you rewrite it to:

```php
$wrapper = new Wrapper($fname);
$sheet = $wrapper->getFirstSheet();
```

...it should work but please don't ask me why this is handled different internally.

**Comment by pilif** [comment]
I know. Or have something else keep the reference around. I have worked around the issue from userland before coming here.

But it should not be possible for userland PHP code to cause a segfault.
