### ISSUE TITLE
Does not build on PHP7.0

### ISSUE THREAD

**Issue by jacobsantos** [iliaal/php_excel#181]
To be clear, it does build on ubuntu, using official repo sources for php and php-dev. I tried the suggestions in #169 and it does not work. It is confusing, since it seems like it is missing the php sources, but the php sources are included and exist. Any input would be appreciated. Installing with ppa:ondrej/php gives the same error as the second dockerfile.

I haven't tried installing using pecl. Will attempt that next, but the current instructions and searching and trying to get the sources working is not having any effect. The only thing I haven't done is put the directory into the ext directory and build from there.

Output Gist is here: https://gist.github.com/jacobsantos/0cffaf74d1abc1a9a0afd3c00fbfe23f
Dockerfile: 

1. https://gist.github.com/jacobsantos/773fc5d630cbf9892d4836714844477f (Dockerfile and build log)
1. https://gist.github.com/jacobsantos/149f424aecfc55701f03ca1aa15fa474

    build arguments are `--build-arg PHP_VERSION="7.0" --build-arg LIBXL_BRANCH="php7"`

**Comment by Jan-E** [comment]
Your docker file uses the master branch, while it should pull the php7 branch.

**Comment by jacobsantos** [comment]
The build arguments are `--build-arg PHP_VERSION="7.0" --build-arg LIBXL_BRANCH="php7"`

**Comment by Jan-E** [comment]
https://gist.github.com/jacobsantos/773fc5d630cbf9892d4836714844477f#file-build-log-L80

3.6.5? Why do not you use LibXL 3.7.2?

**Comment by jacobsantos** [comment]
Using LibXL 3.7.2 fixes issues. There are warnings and notes, but it compiles successfully.

Last time I tried using LibXL with this extension, it did not compile.

**Comment by Jan-E** [comment]
OK. Close the issue, please.
