### ISSUE TITLE
removeRow doc adjustment

### ISSUE THREAD

**Issue by Kiruaalr** [iliaal/php_excel#182]
The doc on the function removeRow in /docs/ExcelSheet.php is not correct.
The second argument isn't the row end but the number of rows to be deleted.
it should be :
	/**
	* Remove rows from row_start for row_numbers rows
	*
	* @param int $row_start 0-based row number
	* @param int $row_numbers number of row to remove
	* @return bool
	*/
	public function removeRow($row_start, $row_numbers)
	{
	} // removeRow

instead of :

	/**
	* Remove rows from row_start to row_end
	*
	* @param int $row_start 0-based row number
	* @param int $row_end 0-based row number
	* @return bool
	*/
	public function removeRow($row_start, $row_end)
	{
	} // removeRow

**Comment by johmue** [comment]
It's directly taken from the official docs:
http://libxl.com/spreadsheet.html#removeRow
