### ISSUE TITLE
I can't use setRowHidden()

### ISSUE THREAD

**Issue by mortezakml** [iliaal/php_excel#185]
Sample Code:
When using this code
$sheet->setRowHidden(10);
Return this error
Call to undefined method ExcelSheet::setRowHidden();

**Comment by johmue** [comment]
I can not reproduce this with the latest php_excel and PHP7.

```php
$b = new \ExcelBook(null, null, true);
$s = new \ExcelSheet($b, 's');
$s->setRowHidden(10, true);
$b->save('setRowHidden_Test.xlsx');
```

**Comment by sgiacinto** [comment]
Using PHP 5.5.7 on Windows and LibXL 3.7.2 licenced I cannot use **setRowHidden()** or **setColHidden()** either.   The error returned is 

Call to undefined method ExcelSheet::setColHidden()
