### ISSUE TITLE
setColHidden hide column anywhere

### ISSUE THREAD

**Issue by orelk** [iliaal/php_excel#186]
This code hide column 2 and 3
$bk = new \ExcelBook(null, null, true);
$sh = new \ExcelSheet($bk, 's');
$sh->setColHidden(2, false);
$sh->setColHidden(3, true);
$bk->save('setColHidden_Test.xlsx');
why?

**Comment by orelk** [comment]
In setColHidden_Test.xlsx, file xl\worksheets\sheet1.xml contain wrong information:
<col min="2" max="2" width="25,7109375" customWidth="true"/>
there should be a comma, then need a point

**Comment by orelk** [comment]
need set setlocale(LC_NUMERIC, 'en_US.UTF-8') before $bk = new \ExcelBook(null, null, true), because the locale was ru_RU.UTF-8

**Comment by johmue** [comment]
This is then a libxl bug since php_excel is only a wrapper and does not generate any excel output.
