### ISSUE TITLE
can't write row 0 in trial version (PHP 7.1)

### ISSUE THREAD

**Issue by garf** [iliaal/php_excel#187]
Hello.
I updated my PHP version from 5.6 to 7.1. And php_excel stopped working.
I use Licensed version of libxl. Compilation goes well. 
But when I try to use library, I get trial version errors.
I tried to set the license key in **ini** file and directly passing it to constructor. Both ways doesn't work for me.
Is php 7.1 supported by this library?

**Comment by belgattitude** [comment]
Hi @garf,

I guess while migrating from 5.6 to 7.1 you've upgraded the extension to https://github.com/iliaal/php_excel/releases/tag/Excel-1.0.2-PHP7 ?

If yes, you should be aware that the latest release ignores license, see #163. Don't use the release but pull the php_excel-php7 branch to build the extension. See also #169 for install instruction or refer this gist: https://gist.github.com/belgattitude/999aee8eb6bd73fd0a7367ad896c76c3 that I used myself in the past.

PHP7.1 work fine for me.

**Comment by garf** [comment]
True. Instead of downloading the release archive I cloned repo and switched to php7 branch. And it worked for me. Thank you.
