### ISSUE TITLE
setMerge is more and more slower when a lot of cell were merged

### ISSUE THREAD

**Issue by ysumadwang** [iliaal/php_excel#188]
for example:

18 col ,  merge(0,1), merge(2,3),merge(4,5),merge(6,7),merge(8,9),merge(10,11)

Row1 - Row300, Merging 300 rows only cost 1sec.
...
Row990 - Row1012, Merging 22 rows  cost 1sec.
...
Row9390 - Row9392, Merging 3 rows cost 1sec.

I have send mail to libxl for supporting  and a new version(3.7.2.7) released  to resolve this issue. 

Version 3.7.2.7 (2017-02-09)
--------------------------------------------------
      - improved speed of Sheet::setMerge() method (removed overlap checking)

I reinstalled php_excel with libxl 3.7.2.7 , but  it's also more and more slower.

A new email send to me ，said：
it seems i have the old libxl.so file on my computer.  checking the version 。

it seems php_excel has not the function of version to check this .
Could you help me  what should I do to use the new version3.7.2.7 ?

**Comment by johmue** [comment]
I can neither find this release nor do i see this mentioned in the changelogs. But what is definitely a good idea is to populate the libxl version in PHP. As well as the Version of the php_excel wrapper. +1

**Comment by ysumadwang** [comment]
@johmue 

Sorry, 3.7.2.7 is not released on libxl's offical website .
They give me the url of   ftp://xlware.com/build/libxl-lin-3.7.2.7.tar.gz
And told me :
You can check the version with the following line in your code:
int version = book->version();

But i don't know how to use it with php.

I edit the example of c in 3.7.2.7, and some code below:

	int version = xlBookVersion(book);
	printf("version:%d",version); // version:50790919

**Comment by johmue** [comment]
Hi, thanks for the link. The version is coded in hex notation {{0x03070207}} which is internally represented as a decimal {{50790919}} in C. If you want to see the hex represenation you have to follow an approach like the one shown here: http://stackoverflow.com/questions/20047598/how-to-make-a-decimal-to-hexadecimal-converter-in-c

**Comment by johmue** [comment]
Here is a simple example to try out [online](https://www.jdoodle.com/c-online-compiler)

{code}
#include<stdio.h>

int main() {
	int x=0x03070207;
	
	printf("x is %i", x);
	printf("\n");
	printf("x is %08x", x);
}
{code}

**Comment by ysumadwang** [comment]
Thanks @johmue .
Could you tell me how can i use the new version libxl 3.7.2.7 ?
I reinstalled  php_excel with libxl 3.7.2.7 ( ./configure  --with-excel --with-libxl-incdir=/home/libxl-3.7.2.7/include_c --with-libxl-libdir=/home/lib/wangjing/libxl-3.7.2.7/lib64).

But Merging is also slower in php .

I make the perfomance.c  in  example of c  , contrast with 3.7.0.1 , merging so fast with 3.7.2.7.

**Comment by johmue** [comment]
I am using libxl on Win, so I'm not an expert for Linux but afaik it does not really matter with which version you compile the php extension since it does not incorporate code from libxl but only creates gateways for php to communicate to libxl. You have to somehow populate the new libxl.so file to your system so that the new library version is used by the system. In windows e.g. you simply replace the old libxl.dll file with the new one and php immediately uses the new version of libxl.

**Comment by Jan-E** [comment]
The newest Win version (not released): ftp://xlware.com/build/libxl-win-3.7.2.8.zip

**Comment by ysumadwang** [comment]
oh, succ .
I **delete the existed excel.so** and reinstall the excel.so with libxl 3.7.2.7 . 
now row 50000,col 20 , merging 8 times per row only cost  34 sec .

**Comment by johmue** [comment]
Added method ExcelBook::getLibXlVersion() in PR #199
