### ISSUE TITLE
It is not working on Mac

### ISSUE THREAD

**Issue by hdwong** [iliaal/php_excel#189]
libxl version: 3.7.2.0

php_excel compile is successful, and I found the following in the Apache error log:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/xxxxx/debug-non-zts-20151012/excel.so' - dlopen(/xxxxx/debug-non-zts-20151012/excel.so, 9): Library not loaded: libxl.dylib\n  Referenced from: /xxxxx/debug-non-zts-20151012/excel.so\n  Reason: image not found in Unknown on line 0

and how I can fix it? Thank you!

**Comment by hdwong** [comment]
fix

**Comment by KaungZawHtet** [comment]
I face that err too. How can I solve it ?

**Comment by johmue** [comment]
Ticket #146 may be helpful.

**Comment by KaungZawHtet** [comment]
thx , it works now
