### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by mdoresse** [iliaal/php_excel#192]
Hi,

I'm trying to compile this extension to use with libxl but I keep getting errors.

I'm runing on a RedHat distribution.

I've followed the installation process for PHP

Everything works fine but step  6 whith the make commnd I have this error (A little bit long .. Sorry for that.)

`php_excel-master]# make
/bin/sh /data/Install/php_excel-master/libtool --mode=compile cc  -I. -I/data/Install/php_excel-master -DPHP_ATOM_INC -I/data/Install/php_excel-master/include -I/data/Install/php_excel-master/main -I/data/Install/php_excel-master -I/usr/local/zend/include/php -I/usr/local/zend/include/php/main -I/usr/local/zend/include/php/TSRM -I/usr/local/zend/include/php/Zend -I/usr/local/zend/include/php/ext -I/usr/local/zend/include/php/ext/date/lib -I/data/Install/libxl-3.6.4.0/include_c  -DHAVE_CONFIG_H  -g -O2   -c /data/Install/php_excel-master/excel.c -o excel.lo
mkdir .libs
 cc -I. -I/data/Install/php_excel-master -DPHP_ATOM_INC -I/data/Install/php_excel-master/include -I/data/Install/php_excel-master/main -I/data/Install/php_excel-master -I/usr/local/zend/include/php -I/usr/local/zend/include/php/main -I/usr/local/zend/include/php/TSRM -I/usr/local/zend/include/php/Zend -I/usr/local/zend/include/php/ext -I/usr/local/zend/include/php/ext/date/lib -I/data/Install/libxl-3.6.4.0/include_c -DHAVE_CONFIG_H -g -O2 -c /data/Install/php_excel-master/excel.c  -fPIC -DPIC -o .libs/excel.o
Dans le fichier inclus à partir de /usr/local/zend/include/php/ext/xml/php_xml.h:35,
          à partir de /data/Install/php_excel-master/excel.c:32:
/usr/local/zend/include/php/ext/xml/expat_compat.h:36:27: erreur: libxml/parser.h : Aucun fichier ou dossier de ce type
/usr/local/zend/include/php/ext/xml/expat_compat.h:37:36: erreur: libxml/parserInternals.h : Aucun fichier ou dossier de ce type
/usr/local/zend/include/php/ext/xml/expat_compat.h:38:25: erreur: libxml/tree.h : Aucun fichier ou dossier de ce type
/usr/local/zend/include/php/ext/xml/expat_compat.h:39:25: erreur: libxml/hash.h : Aucun fichier ou dossier de ce type
In file included from /usr/local/zend/include/php/ext/xml/php_xml.h:35,
                 from /data/Install/php_excel-master/excel.c:32:
/usr/local/zend/include/php/ext/xml/expat_compat.h:44: erreur: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘XML_Char’
/usr/local/zend/include/php/ext/xml/expat_compat.h:46: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:47: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:48: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:49: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:50: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:51: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:52: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
In file included from /usr/local/zend/include/php/ext/xml/php_xml.h:35,
                 from /data/Install/php_excel-master/excel.c:32:
/usr/local/zend/include/php/ext/xml/expat_compat.h:53: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:54: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:55: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:56: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:67: erreur: expected specifier-qualifier-list before ‘xmlChar’
/usr/local/zend/include/php/ext/xml/expat_compat.h:124: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:125: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:126: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:129: erreur: expected declaration specifiers or ‘...’ before ‘XML_StartElementHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:129: erreur: expected declaration specifiers or ‘...’ before ‘XML_EndElementHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:130: erreur: expected declaration specifiers or ‘...’ before ‘XML_CharacterDataHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:131: erreur: expected declaration specifiers or ‘...’ before ‘XML_ProcessingInstructionHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:132: erreur: expected declaration specifiers or ‘...’ before ‘XML_DefaultHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:133: erreur: expected declaration specifiers or ‘...’ before ‘XML_UnparsedEntityDeclHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:134: erreur: expected declaration specifiers or ‘...’ before ‘XML_NotationDeclHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:135: erreur: expected declaration specifiers or ‘...’ before ‘XML_ExternalEntityRefHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:136: erreur: expected declaration specifiers or ‘...’ before ‘XML_StartNamespaceDeclHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:137: erreur: expected declaration specifiers or ‘...’ before ‘XML_EndNamespaceDeclHandler’
/usr/local/zend/include/php/ext/xml/expat_compat.h:138: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:140: erreur: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/expat_compat.h:145: erreur: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
In file included from /data/Install/php_excel-master/excel.c:32:
/usr/local/zend/include/php/ext/xml/php_xml.h:43: erreur: expected specifier-qualifier-list before ‘XML_Char’
/usr/local/zend/include/php/ext/xml/php_xml.h:50: erreur: expected specifier-qualifier-list before ‘XML_Char’
/usr/local/zend/include/php/ext/xml/php_xml.h:94: erreur: expected specifier-qualifier-list before ‘XML_Char’
/usr/local/zend/include/php/ext/xml/php_xml.h:137: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/local/zend/include/php/ext/xml/php_xml.h:138: erreur: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/data/Install/php_excel-master/excel.c: In function ‘zim_ExcelBook___construct’:
/data/Install/php_excel-master/excel.c:1309: erreur: expected ‘)’ before ‘XML_Char’
/data/Install/php_excel-master/excel.c:1309: attention : transtypage d'un pointeur vers un entier de taille différente
/data/Install/php_excel-master/excel.c:1309: erreur: expected ‘)’ before ‘XML_Char’
/data/Install/php_excel-master/excel.c:1309: attention : transtypage d'un pointeur vers un entier de taille différente
/data/Install/php_excel-master/excel.c:1309: attention : assignment makes pointer from integer without a cast
/data/Install/php_excel-master/excel.c:1310: erreur: expected ‘)’ before ‘XML_Char’
/data/Install/php_excel-master/excel.c:1310: attention : transtypage d'un pointeur vers un entier de taille différente
/data/Install/php_excel-master/excel.c:1310: erreur: expected ‘)’ before ‘XML_Char’
/data/Install/php_excel-master/excel.c:1310: attention : transtypage d'un pointeur vers un entier de taille différente
/data/Install/php_excel-master/excel.c:1310: attention : assignment makes pointer from integer without a cast
make: *** [excel.lo] Erreur 1
`
Do you have any clue ???

Very kind regards,

Matthieu

**Comment by ysumadwang** [comment]
https://github.com/iliaal/php_excel/issues/172

If you compile php_excel as a shared extension on Linux you need to provide the path to the libxml directory. e.g. on Ubuntu you need to compile with --with-libxml-dir=/usr/include/libxml2.

**Comment by johmue** [comment]
Does it help to follow [this](http://qiita.com/hirohiro77/items/3ab7242fabaed2a9153f) approach? It's Japanese but the code snippets are fine though.
