### ISSUE TITLE
Call to undefined method ExcelSheet:setColHidden()

### ISSUE THREAD

**Issue by sgiacinto** [iliaal/php_excel#193]
Using PHP 5.5.7 on Windows, LibXL 3.7.2 licenced, php_excel file **php_excel-20140606-5.6-nts-vc11-x86.zip**

 I cannot use **setRowHidden()** or **setColHidden()**. The error returned is

**Call to undefined method ExcelSheet::setColHidden()**

Please help, thanks.

**Comment by johmue** [comment]
Thanks to the efforts of @Jan-E you can grab compiled up-2-date versions of php_excel for Win here: https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by sgiacinto** [comment]
Thanks, that works great.
