### ISSUE TITLE
wrap text not working

### ISSUE THREAD

**Issue by sgiacinto** [iliaal/php_excel#194]
Hello, I cannot get the wrap function to work. 

```
$wrap_text = $ex->addFormat();
$wrap_text->wrap(true);	
```
... 
`$xlSheet1->setRowHeight(2,30, $wrap_text); `

Doesn't cause anything to happen, the text still expands past the cell boundary even though there is space for it to wrap. 

<img width="145" alt="screen shot 2017-03-31 at 16 14 24" src="https://cloud.githubusercontent.com/assets/7951533/24554251/2c22e41e-162d-11e7-8f00-b0ebd037ac9d.png">

**Comment by johmue** [comment]
Seems it does not work with setRowHeight() but to me it looks like the libxl lib does not work properly here. For the moment you might want to get along with the normal write() method.

```php
$b = new \ExcelBook();
$format = $b->addFormat();
$format->wrap(true);

$s = new \ExcelSheet($b, 'Sheet 1');
$s->write(1, 1, 'foo bar baz', $format);
```

**Comment by sgiacinto** [comment]
Thanks
