### ISSUE TITLE
Cannot set validation for a cell / Validation setting being removed if a formula

### ISSUE THREAD

**Issue by sgiacinto** [iliaal/php_excel#195]
Hello,
If I setup a file in Excel with simple cell validation against a named range, this works when the file is updated and saved in php_excel. 

e.g.   when source =       "=Ethnicity"  and there is a named range called Ethnicity. This range is added by php_excel dynamically. 

However if I have a formula as the list's validation source, the validation configuration is deleted when saved.

`=INDIRECT(VLOOKUP($C$3;LOOKUPS!$L$1:$M$9;2))`

which is looking at the value in $C$3 (the result of "Ethnicity") and looking it up in the range L$1:M$9 and using the name there as the named range to list. 

The formula  =INDIRECT(... above is completely removed and there is no data validation on the cell after saving it in php_excel.      

Anyone have any ideas?

**Comment by sgiacinto** [comment]
Sorry, forgot to add, this works in Excel.

**Comment by johmue** [comment]
Is it possible for you to post a very basic example that outlines the core problem - maybe 5-10 lines of php code? Thx

**Comment by sgiacinto** [comment]
Sure. I have an existing excel sheet set up as a template. This has a lookup sheet that is populated dynamically from the database. The entries are dynamic however the column positions and counts are the same, so I know column 8, for example, is ethnicity.  

So I set the lookups like this: 

```
    $xlSheet1 = $ex->getSheetByName("LOOKUPS");
	$xlSheet1->writeCol(0,getArray($fsm_d));
	$xlSheet1->writeCol(1,getArray($fsm6_d));
	$xlSheet1->writeCol(2,getArray($sen_d));
	$xlSheet1->writeCol(3,getArray($eal_d));
	$xlSheet1->writeCol(4,getArray($ytic_d));
	$xlSheet1->writeCol(5,getArray($ppi_d));
	$xlSheet1->writeCol(6,getArray($ilc_d));
	$xlSheet1->writeCol(7,getArray($gender_d));
	$xlSheet1->writeCol(8,getArray($ethnicity_d));
	
	$group = array("English Additional Language", "Ethnicity", "Free school meals", "FSM Ever", "Gender", "Looked after", "Pupil Premium", "Special Educational Needs", "YTIV"); 
	$code =  array("EAL", "Ethnicity" ,"FSM", "FSME", "Gender", "ILC", "PPI", "SEN", "YTIV");
 
	$xlSheet1->writeCol(11,$group);
	$xlSheet1->writeCol(12,$code);
		
	$xlSheet1->setNamedRange("FSM",0,count($fsm_d),0,0);
	$xlSheet1->setNamedRange("FSME",0,count($fsm6_d),1,1);
	$xlSheet1->setNamedRange("SEN",0,count($sen_d),2,2);
	$xlSheet1->setNamedRange("EAL",0,count($eal_d),3,3);
	$xlSheet1->setNamedRange("YTIC",0,count($ytic_d),4,4);
	$xlSheet1->setNamedRange("PPI",0,count($ppi_d),5,5);
	$xlSheet1->setNamedRange("ILC",0,count($ilc_d),6,6);
	$xlSheet1->setNamedRange("Gender",0,count($gender_d),7,7);
	$xlSheet1->setNamedRange("Ethnicity",0,count($ethnicity_d),8,8);
	$xlSheet1->setNamedRange("Groups",0,count($group),11,11);

```

I then create copies of a sheet (pre made in the template) that has a **validation reference** to the named ranges, i.e.  with the source portion as 

`=Ethnicity `

This functions great.  

Problem is, if I pre-create a cell that has a FORMULA (not a direct reference to a named range, but rather a formula) the entire validation part is removed when saved by php_excel. 

This is how I am creating my sheets form the template: 

```
$xlSheet1    = $ex->copySheet($newtitle, 0);
	
		$h = 1;
		for($y = 0; $y < count($header); $y++) {
			
			$dta = array_map('getVal' , $header[$y]); 
		
			if($xlSheet1) {
			
				$xlSheet1->writeRow($h, $dta, 15);	
				$h++;
			}
		}	
	
```

The fields with validation and formula are in a part of the sheet that is NOT written over. The drop down with a reference directly to the named range works fine, the second box with a formula does not show up at all. 

In Excel, the behaviour is as such: 

<img width="340" alt="screen shot 2017-04-02 at 21 10 09" src="https://cloud.githubusercontent.com/assets/7951533/24590301/06ad9d9a-17eb-11e7-8231-6085d372a6cc.png">

then selecting a value updates the second box: 

<img width="329" alt="screen shot 2017-04-02 at 21 10 45" src="https://cloud.githubusercontent.com/assets/7951533/24590306/16f6cce4-17eb-11e7-8e39-e6192432e629.png">

**Comment by sgiacinto** [comment]
Here is some more info - I have reduced it down to something understandable. 
The template file worksheet contains this validation node: 

```
<dataValidations count="2">
<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="C3">
<formula1>Groups</formula1>
</dataValidation>
<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="C4">
<formula1>INDIRECT(C3,0)</formula1>
</dataValidation>
</dataValidations>
```

The first node which is a direct reference to a dynamically created named range, functions fine. 
The second node, which is a dynamic reference to the value from the first node, is completely removed when opened in php_excel.

**Comment by johmue** [comment]
If this can be tracked down to Excels XML it's an issue with the LibXL library. Since the PHP extensions is just a wrapper around the library you should probably point libxls support to this issue here so that they can investigate.

**Comment by johmue** [comment]
Can you please check with latest libXL 3.8.0?
