### ISSUE TITLE
Unable to set password on protect

### ISSUE THREAD

**Issue by wengkiat** [iliaal/php_excel#196]
Hi, 

I am trying to protect my excel sheet with the method below but do not know how to set a password for it as it accepts a boolean.

May I know how would I be able to proceed?

Thanks!
/**
* Protects or unprotects the worksheet
	*
	* @see ExcelSheet::protect()
	* @param bool $value
	* @return void
	*/
	public function setProtect($value)
	{
	} // setProtect

**Comment by johmue** [comment]
As far as I can see the PHP5 branch and PHP7 are not in sync regarding protection. it should be implemented in PHP7 branch and documented accordingly.

```
	/**
	* Protects or unprotects the worksheet
	*
	* @see ExcelSheet::protect()
	* @param bool $value
	* @param string $password (optional, default="")
	* @param int ExcelSheet::PROT_ALL (optional, default=ExcelSheet::PROT_DEFAULT)
	* @return void
	*/
	public function setProtect($value, $password="", $enhancedProtection=ExcelSheet::PROT_DEFAULT)
	{
	} // setProtect
```
