### ISSUE TITLE
Can you please implement new libxl method addDataValidation ?

### ISSUE THREAD

**Issue by youngvan** [iliaal/php_excel#198]
It's just added to libxl library

http://libxl.com/spreadsheet.html#addDataValidation

**Comment by johmue** [comment]
PR is already filed :)

**Comment by youngvan** [comment]
Trying to make a build from your branch and it fails (

checking for excel includes... found in ../libxl-3.8.0.0/include_c
checking for excel libraries... found in ../libxl-3.8.0.0/lib
checking for libxml2... not found
checking for xlCreateBookCA in -lxl... no
configure: error: excel module requires libxl >= 2.4.3

i am doing something wrong?

./configure --with-libxl-incdir=../libxl-3.8.0.0/include_c --with-libxl-libdir=../libxl-3.8.0.0/lib

**Comment by youngvan** [comment]
Thank's a lot!

Any ideas how to pass list to make a list validation?

I am trying 
`<?php
// init excel work book as xlsx

$xlBook = new ExcelBook(null, null, true);
$xlBook->setLocale('UTF-8');

// add sheet to work book
$xlSheet1 = $xlBook->addSheet('Sheet1');

$xlSheet1->addDataValidation(ExcelSheet::VALIDATION_TYPE_LIST, ExcelSheet::VALIDATION_OP_EQUAL,0, 5, 0, 1, array('John', 'Jane'));
$xlBook->save('tmp/test6.xlsx');


and nothing

**Comment by youngvan** [comment]
and looks like xlsx file inside totally empty and doesn't contain any validation rules

**Comment by johmue** [comment]
I haven't tested it in much detail so far but I assume it's a simple comma separated list of values. Since the API expects a simple string.

The other possibility that comes to my mind is to add them one by one - but I don't think it works this way.

**Comment by youngvan** [comment]
With calls like this
`$xlSheet1->addDataValidation(ExcelSheet::VALIDATION_TYPE_LIST, ExcelSheet::VALIDATION_OP_EQUAL,0, 5, 0, 5, "John,Jane");`

i am getting Segmentation fault (core dumped)

**Comment by johmue** [comment]
Uh. ...does it work w/o comma? I think I have tested it with a single word and it worked just fine. If it works w/o comma I think it's not a bug on php_excels side.

**Comment by johmue** [comment]
Does it help to add a value to $val_2? It's ignored by the libxl but may cause the problem. Thx

**Comment by youngvan** [comment]
Found it

you should pass reference to range

work this way

`$xlSheet1->addDataValidation(ExcelSheet::VALIDATION_TYPE_LIST, ExcelSheet::VALIDATION_OP_EQUAL,0, 5, 0, 5, '$A$2:$A$7','');`

Thanks a lot!

**Comment by youngvan** [comment]
Is it possible to merge it to master/dev branch?

**Comment by hei1046035362** [comment]
but, specify a list of values in quotes here:

  sheet->addDataValidation(VALIDATION_TYPE_LIST, VALIDATION_OP_EQUAL,
  6, 6, 6, 6, L"first,second,third");

**Comment by hei1046035362** [comment]
But,It still doesn't work in that way in C++:

 specify a list of values in quotes here:

  sheet->addDataValidation(VALIDATION_TYPE_LIST, VALIDATION_OP_EQUAL,
  6, 6, 6, 6, L"first,second,third");


and cause the excel fix it to normal.
