### ISSUE TITLE
\ExcelSheet->readRow(...) Fails

### ISSUE THREAD

**Issue by adam-djangophi** [iliaal/php_excel#202]
When `readRow()` on row 4 of the attached xls sheet is called a seg fault occurs.
```[04-May-2017 15:52:35] WARNING: [pool www] child 2476 exited on signal 11 (SIGSEGV) after 0.037520 seconds from start```
[erroneous.xlsx](https://github.com/iliaal/php_excel/files/976428/erroneous.xlsx)
I have tried this with the last version 3.8.0
This occurs at the column 06/08/-27404  which is supposed to be a date, when changed to a valid date the error stops.

**Comment by johmue** [comment]
The file is probably not a proper xlsx file. I've not tested the file because it looks suspicious. I tried to etxract it and it does not return a normal xlsx file structure.
