### ISSUE TITLE
Docker image using alpine linux

### ISSUE THREAD

**Issue by FrodeMMeling** [iliaal/php_excel#210]
I am trying to get php_excel to work inside php:5.6-fpm-alpine docker image.

Not so easy since alpine does not use glibc. Is it possible to get it to compile using uclibc?

**Comment by jeflores7** [comment]
@FrodeMMeling Did you ever get this working? I'm also trying to get php_excel to work in an alpine linux docker image with php-fpm 5.6 (specifically php:5.6.32-fpm-alpine3.4).

@iliaal I have uploaded my **config.log** file if you have time to help take a look. 
[config.log](https://github.com/iliaal/php_excel/files/1674976/config.log)

I got to this point by installing the following packages at least `build-base gcc g++ libc6-compat abuild make`. I believe that is enough to compile the software based on https://wiki.alpinelinux.org/wiki/How_to_get_regular_stuff_working

I'm actively working on this so if more info is required I'm open to working together

**Comment by johmue** [comment]
Have you already tried to compile with the very latest version of libx? ftp://xlware.com/build/

**Comment by FrodeMMeling** [comment]
No, I gave up and went over to Bitnami minideb instead: https://github.com/bitnami/minideb

**Comment by jeflores7** [comment]
@johmue I did try against 3.7.0, but the changelog of this repo states that it added support for LibXL 3.6.3 last. Not sure if it will work with the latest version, I'll give it a shot.

Ahh, thanks @FrodeMMeling

**Comment by cjsfj** [comment]
FWIW I tried this with 3.8.2.10 and it didn't work...

Getting error:

`configure: error: excel module requires libxl >= 2.4.3`

Hoping someone has figured this out! ;(

**Comment by cjsfj** [comment]
Turns out LibXL is compiled with glibc, but Alpine uses musl.. 

So I was able to recompile LibXL from source in my environment, but now I'm back stuck on this.

I'm a step away from switching to minideb. But I'd really prefer to use alpine like the rest of my stack.

**Comment by raiviskrumins** [comment]
Got hit by this issue today
Are there any plans to fix this, or should I also look into https://github.com/bitnami/minideb ?

**Comment by cjsfj** [comment]
I think there is potential to get this finctioning. However we had to move to centos for other dependencies, so the work was stopped on my end.
