### ISSUE TITLE
License check fail in LibXL 3.8.1

### ISSUE THREAD

**Issue by youngvan** [iliaal/php_excel#212]
Hi, 

i am testing LibXL 3.8.1 with 380 branch 
https://github.com/iliaal/php_excel/pull/199

And license doesn't work

<?php

$xlBook = new \ExcelBook("NAME", "KEY", true);
$xlSheet1 = $xlBook->addSheet('Sheet1');
xlSheet1->write(0, 0,"hello");
$xlBook->save('test.xlsx’);

——

gives me

PHP Warning:  ExcelSheet::write(): Failed to write cell in row 0, column 0 with error 'can't write row 0 in trial version' in /home/ddc/1.php on line 17

LibXL 380 with same branch works fine and license is correct

**Comment by johmue** [comment]
Tested with latest PHP 7.2.0RC2-nts-32bit and libxl 3.8.1 on Win 10. Works perfectly fine.

```php
$user = utf8_decode(get_cfg_var('excel.license_name'));
$key = utf8_decode(get_cfg_var('excel.license_key'));

$b = new \ExcelBook($user, $key, true);
$s = new \ExcelSheet($b, 'Table1');

var_dump($s->isLicensed()); // bool(true)
```

**Comment by imTigger** [comment]
+1
License in php.ini doesn't work in 3.8.2

**Comment by belgattitude** [comment]
Works for me. Tested with PHP7.2, libxl-3.8.2 under Ubuntu 16.04 64bits.

PS: My install: https://gist.github.com/belgattitude/69d3245227d4cc284996e3f0a1bc0033
