### ISSUE TITLE
Invalid order of parameters for \ExcelAutoFilter::setRef()

### ISSUE THREAD

**Issue by xperseguers** [iliaal/php_excel#216]
According to http://www.libxl.com/autoFilter.html, LibXL provides parameters in following order

1. `rowFirst`
2. `rowLast`
3. `colFirst`
4. `colLast`

This differs from `\ExcelAutoFilter::setRef()` where parameters are mixed-up and declared as

1. `rowFirst`
2. `colFirst`
3. `rowLast`
4. `colLast`

**Comment by doppiogancio** [comment]
I saw and reported a similar problem `ExcelSheet::setNamedRange(string name, int row, int col, int to_row, int to_col [, int scope_id])`

**Comment by xperseguers** [comment]
@doppiogancio Mind referencing where your report is?

**Comment by doppiogancio** [comment]
Sorry, my fault. I created a Pull Request with this trivial change
https://github.com/iliaal/php_excel/pull/204
