### ISSUE TITLE
Transfer project to a github organization

### ISSUE THREAD

**Issue by johmue** [iliaal/php_excel#221]
Hi @iliaal,

Do you mind to transfer this project to a github organization where more people are allowed to commit and handle issues? I believe it would help the project to keep up with libxls development track.

Thanks & Best,
Johannes

**Comment by xperseguers** [comment]
Quite strange that @iliaal as absolutely no contributions anymore to any GitHub project in the last year...

**Comment by johmue** [comment]
Hi @iliaal,

Do you have an opinion on transferring the php_excel project into a github organization?

Thanks & Best,
Johannes

**Comment by johmue** [comment]
Hi @iliaal,
Another year has passed and I would like to remind you that a lot of people use this software with great success and gratitude. It would be really awesome if you find the time to move it into an organization. Thank you very much in advance.
