### ISSUE TITLE
Cant find AutoFilter functions

### ISSUE THREAD

**Issue by nrobuk** [iliaal/php_excel#222]
Good day!
Cannt find functions for http://www.libxl.com/autoFilter.html

Please Help! :)

**Comment by johmue** [comment]
It’s supported only for PHP 7+ which is in a separate branch from master ...
https://github.com/iliaal/php_excel/tree/php7

**Comment by johmue** [comment]
If you also want to use the latest features of libxl 3.8.0 - there is still a pending PR for this...

**Comment by nrobuk** [comment]
I need that for PHP 5.6

**Comment by johmue** [comment]
Sorry - it’s not available for PHP 5.x currently and I don’t think that someone will send a PR for that.

**Comment by nrobuk** [comment]
how to define Z_OBJ_P for php5 in excel.c
I have no exps in developing PHP Extensions *blush*

**Comment by nrobuk** [comment]
I'm done with lib, but I still have problems. The addDataValidation function does not work. Maybe someone can see the eyes of the master what is the problem?
