### ISSUE TITLE
./buildconf: No such file or directory

### ISSUE THREAD

**Issue by aphofstede** [iliaal/php_excel#227]
The docs say to run `./buildconf --force` when building for php7, but I seem to be missing something?

```
# ./buildconf --force
bash: ./buildconf: No such file or directory
```

**Comment by johmue** [comment]
It's part of the [php source code](https://github.com/php/php-src/blob/master/buildconf). If you are using Linux you may need to install the `php-dev` package first if you only want to compile the extension w/o php source code.

**Comment by aphofstede** [comment]
Ah I see, it does indeed say to `cd` into the php source. 
My script does:
```bash
  # ^ ... copy libxl deps to /usr/lib/libxl and install libxml2-dev ...
  phpize && pwd && ./configure --with-libxl-libdir=/usr/lib/libxl/lib64 --with-libxl-incdir=/usr/lib/libxl/include_c
  export C_INCLUDE_PATH=/usr/include/libxml2:$C_INCLUDE_PATH
  make && make install
```
This works, so `phpize` seems to work as well. Any differences we should know about?
