### ISSUE TITLE
I want to buy Libxl but I don't know what to choose. I am currently using mac and linux as dual boot. I want to use Libxl for php. Does buying license key for mac also work on linux when I extend that key at php.ini?

### ISSUE THREAD

**Issue by KaungZawHtet** [iliaal/php_excel#228]

**Comment by johmue** [comment]
Don‘t think so. You have to chose an OS where you want to use it as far as I know. Otherwise you have to buy a license which runs an all required platforms. But please ask libxl support!

**Comment by KaungZawHtet** [comment]
If so, do I need to buy license for VPS that host my web app ? ( if yes, I think I have to buy 2 license for both of my development pc and VPS )

**Comment by johmue** [comment]
To be honest - I don‘t know. Please ask libxl support. @dmytroskr can you please catch up on this. Thx

**Comment by xperseguers** [comment]
You need to buy 2 licences, one for your development PC (Windows or Mac in your case) and one for your server, Linux. I did have to buy mac+linux...
