### ISSUE TITLE
Problem with background color

### ISSUE THREAD

**Issue by syrm** [iliaal/php_excel#23]
$excel = new \ExcelBook(null, null, 1);
$excel->setRgbMode(true);
$sheet = $excel->addSheet("Worksheet");
$format = $excel->addFormat();
$color = $excel->colorPack(200, 217, 220);
$format->fillPattern(\ExcelFormat::FILLPATTERN_SOLID);
$format->patternBackgroundColor($color);
$sheet->write(1, 1, 'Test', $format);

The background of cell is black.

**Comment by billybraga** [comment]
I have the same problem. How did you solve it?
