### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by xperseguers** [iliaal/php_excel#231]
Is there anything special so that this library may be used with PHP 7.2?

I compiled it successfully for PHP 7.0 and PHP 7.1 but when I do the same for PHP 7.2,

```
php -m
```

or `phpinfo();` do not return `excel` at all. And I see no error message.

**Comment by johmue** [comment]
I can assure you that it works with Win + PHP 7.2 but it should also work for Linux.

**Comment by xperseguers** [comment]
Don't really know what happened but it did not load in `phpinfo` until I changed the default CLI version of my MAMP Pro install and all of a sudden, it appears although module was properly marked for loading in `php.ini` and `excel.so` was in the correct directory.

Anyway, it works now!
