### ISSUE TITLE
Getting started doesn't work?

### ISSUE THREAD

**Issue by t2-yoshida** [iliaal/php_excel#233]
I use Windows 10/64bit, PHP 7.2.5 on Apache 2.4 build VC15.
An error occurred in Getting started.

`Warning: ExcelSheet::write(): Failed to write cell in row 1, column 1 with error 'ok' in path/to/php`

following code.

`$xlSheet2->write($row, $col, $date->getTimestamp(), $dateFormat, \ExcelFormat::AS_DATE);`

Excel file is outputed, but nothing is outputed on sheet2.
Is there any solution?

**Comment by youngvan** [comment]
got the same error after upgrading to php 7.2

running linux with license

**Comment by youngvan** [comment]
I am able to reproduce it

try this code

`<?php

$data = array (
	0 => 'test me hard'
);


$xlBook = new \ExcelBook(null, null, true);
$xlBook->setLocale('UTF-8');
$xlSheet1 = $xlBook->addSheet('Sheet1');

var_dump($data);
array_walk($data, function(&$field) {
		$field = (string)$field;
	});
var_dump($data);

$xlSheet1->writeRow(0, $data);
`

**Comment by youngvan** [comment]
the bug happens ONLY with array_walk call, even if it's not changing data

crossposted to bugs.php.net https://bugs.php.net/bug.php?id=76343 - but i think i will be banned there

**Comment by youngvan** [comment]
I got reply from bugs.php.net

This is a bug in the extension, which does not support references. Please file a bug there, it's missing a ZVAL_DEREF() in the array processing function.

**Comment by youngvan** [comment]
@belgattitude  can you check it?

**Comment by youngvan** [comment]
moved here https://github.com/iliaal/php_excel/issues/234
