### ISSUE TITLE
Compiling new DLL for Windows

### ISSUE THREAD

**Issue by alois-trancy** [iliaal/php_excel#238]
Hi! I am using Windows for development and is it possible to compile a new php_excel.dll in the given source? If possible, can you teach me or give me link how to?

The snapshot provided for windows is already outdated.

**Comment by johmue** [comment]
You can find up-to-date snapshots here: 
https://www.apachelounge.com/viewtopic.php?t=6359

A not so well maintained introduction how to compile php_excel for windows can be found here:
https://github.com/johmue/win-php-sdk-builder
