### ISSUE TITLE
Pre-build packages for Windows 

### ISSUE THREAD

**Issue by yherus** [iliaal/php_excel#240]
How to build php 7.2 Extension for windows

**Comment by johmue** [comment]
You can download pre-compiled dlls for PHP-Release-Versions here:
https://www.apachelounge.com/viewtopic.php?t=6359

and for PHP-QA-Versions here:
https://www.apachelounge.com/viewtopic.php?t=6617

...no warranties for anything. It's a third party project but worked very well for me. I typically use an official PHP download and use the php_excel.dll from the package. You still need to put the libxl.dll in your PHP.
