### ISSUE TITLE
Work with Pivot or Dynamic tables

### ISSUE THREAD

**Issue by seyfer** [iliaal/php_excel#244]
I have checked this link and given php classes stubs.
https://ilia.ws/index.php?url=archives/222-PHP-Excel-Extension.html#c192935

The tests, which are supposed to be docs, are not named meaningfully. 

Cannot figure out how to work with Pivot or Dynamic tables with php_excel.

If there is a test showing it - please point me to it. Thanks.

**Comment by johmue** [comment]
AFAIK libxl does not support Pivot or Dynamic tables - please check the official documentation http://libxl.com/documentation.html

`php_excel` documentation can be found in the folder `/doc`

**Comment by seyfer** [comment]
@johmue what about Autofilters?

**Comment by johmue** [comment]
It’s available in the php7 branch (https://github.com/iliaal/php_excel/tree/php7/docs). For the php5 branch you have to check @nrobuk fork (see issue #222)
