### ISSUE TITLE
Fatal error: 'break' not in the 'loop' or 'switch' context in \PHPExcel\PHPExcel\Calculation\Functions.php on line 581 

### ISSUE THREAD

**Issue by swapnilb0506** [iliaal/php_excel#245]
Fatal error: 'break' not in the 'loop' or 'switch' context in \PHPExcel\PHPExcel\Calculation\Functions.php on line 581

This error come out for when download excel file open in excel 2007.

Please fix this problem . Thank you

**Comment by johmue** [comment]
@swapnilb0506 this project is not PHPExcel - please read my comment in reply to yours on issue #141

**Comment by swapnilb0506** [comment]
@johmue  I will try  replace the php version  1.8

**Comment by swapnilb0506** [comment]
@johmue I replace the php version 1.8
but give same problem

**Comment by johmue** [comment]
@swapnilb0506 https://github.com/PHPOffice/PHPExcel

**Comment by swapnilb0506** [comment]
@johmue  I  try  you mentioned  phpExcel  version  but not solve  problem    
Exactly problem for  when export excel sheet not  content show in excel 2007
Please Solve
