### ISSUE TITLE
[doc] php_excel stubs and install docs (howto)

### ISSUE THREAD

**Issue by belgattitude** [iliaal/php_excel#251]
Not an issue but sharing tips for php_excel installation and stubs to enable autocompletion.

The repo is https://github.com/belgattitude/php_excel_dev

Hope it helps newcomers, I intend to maintain this repo for a while. php_excel is an amazing solution. Thanks @iliaal and others

Doc:

### Stubs

Useful for autocompletion: ```composer require soluble/php_excel_dev --dev```

-----

### php_excel install tips

In order to compile the [ilia/php_excel](https://github.com/iliaal/php_excel) you must have libXL installed and the php development packages installed (phpize, phpconfig).

On Ubuntu:

```sh
sudo apt-get install php-dev
```

> 
> *Alternatively suffix with the php version if you're using the ondrej/php ppa:*
>
> ```sh
> sudo apt-get install php7.3-dev
> ```
>

Once done, you can either use one of the bash scripts below :

| PHP  | Distribution    | Gist                                                                                                |
| ---- | --------------- |--------------------------------------------------------------------------------------------------- |
| 7.3  | Ubuntu [ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php) ppa  | [install_phpexcel_php73.sh](https://gist.github.com/belgattitude/7af75780e13530fd2895607079499318)  |
| 7.2  | Ubuntu [ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php) ppa  | [install_phpexcel_php72.sh](https://gist.github.com/belgattitude/69d3245227d4cc284996e3f0a1bc0033)  |
| 7.1  | Ubuntu [ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php) ppa  | [install_phpexcel_php71.sh](https://gist.github.com/belgattitude/999aee8eb6bd73fd0a7367ad896c76c3)  |

Or make a manual installation :
 
## LibXL

The [libxl](http://www.libxl.com) static binaries can easily be installed:

```sh
sudo mkdir /opt/libxl-3.8.2;
wget -qO- http://www.libxl.com/download/libxl-lin-3.8.2.tar.gz | sudo tar zxvf - --strip 1 --directory /opt/libxl-3.8.2
```

## PHP extension

Download and unzip the php7 branch:

```sh
wget -qO- https://github.com/iliaal/php_excel/archive/php7.tar.gz | tar zxvf - --directory /tmp
``` 

Build the extension;

```sh
cd /tmp/php_excel-php7; 
./configure --with-php-config=`which php-config` \
            --with-libxl-incdir=/opt/libxl-3.8.2/include_c/ \
            --with-libxl-libdir=/opt/libxl-3.8.2/lib64/ \
            --with-excel=/opt/libxl-3.8.2 && \
make && \
make install
```

> In case you're using multiple php versions, you can generally suffix
> the phpize and phpconfig commands like `phpize-7.3`, `php-config-7.3`...

Then register the extension in your php.ini:

```ini
extension=excel.so
```

> For ondrej/php ppa 
>
> ```sh
> echo "extension=excel.so" > /tmp/excel.ini;
> sudo cp /tmp/excel.ini /etc/php/php7.3/mods-available/excel.ini; 
> sudo phpenmod -v 7.3 excel;
>```
>

**Comment by do-io** [comment]
Added to Wiki
https://github.com/iliaal/php_excel/wiki
