### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by lmstanky** [iliaal/php_excel#253]
Hi

The PHP extension for LibXL seems to use a lot of memory. I'm trying to write to between 1,000,000 and 8,000,000 cells, granted, but this is for an XLSX file that's only about 15MB maximum, and trying to produce it pushes the peak memory usage of the PHP FastCGI process to approximately 1GB.

Can you verify this is just how much memory the extension uses? Or is this just a PHP thing?

Thanks :)

**Comment by johmue** [comment]
you can read about a PHPExcel analysis (speed and memory here):
https://blog.mayflower.de/4922-Performant-Handling-Excel-Files-PHP.html
