### ISSUE TITLE
Latest Windows pre-build

### ISSUE THREAD

**Issue by lmstanky** [iliaal/php_excel#256]
There are pre-builds available for Windows, but they're outdated by 2 years and I'm struggling to compile the latest release (which includes the auto width functions), 1.0.2 for PHP 5.

Is a pre-built version for this available anywhere, or is compiling it my only option?
Thanks :)

**Comment by Jan-E** [comment]
Try the ones that are in the zipfiles at https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by lmstanky** [comment]
Thanks for your suggestion. I took the php_excel.dll from the 5.6 build listed, but got an error saying ExcelBook doesn't exist as a class

**Comment by Jan-E** [comment]
Which libxl version are you using? The DLL's are compiled with libxl-win-3.8.5.7 downloaded from ftp://xlware.com/build
See the phpinfo.htm inside the zips for details.

**Comment by lmstanky** [comment]
Right now I'm using 5.6-nts-vc11-x86 from https://windows.php.net/downloads/pecl/snaps/excel. Looking at my phpinfo, that's version 3050300

**Comment by Jan-E** [comment]
Libxl 3.5.3 is a really old version. If you cannot compile php_excel.dll yourself the only way is upgrading Libxl

**Comment by lmstanky** [comment]
I don't quite understand then. I downloaded the latest version of LibXL and took the DLL from that archive and installed it in my PHP directory, but I'm still stuck using a heavily outdated version? How do I compile php_excel then?

**Comment by lmstanky** [comment]
I don't know what I was doing wrong, but once again I took php_excel from one of the builds you listed, downloaded the latest version of LibXL from their website and now I've managed to update it. Not the first silly mistake I've ever made, won't be the last :')
