### ISSUE TITLE
USE THIS LIBRARY IN WINDOWS USING XAMPP PHP APACHE

### ISSUE THREAD

**Issue by ankesh4040** [iliaal/php_excel#259]
HOW TO USE WINDOWS Pre-build packages  IN PHP VIA XAMPP??

**Comment by johmue** [comment]
Hi, you can try the builds from https://www.apachelounge.com/viewtopic.php?t=6359
They are up-2-date and compiled for the latest PHP versions.

**Comment by Jan-E** [comment]
@ankesh4040 Be sure to have a recent libxl.dll in the PHP directory.
