### ISSUE TITLE
Error when trying to hide a sheet with setHidden(true)

### ISSUE THREAD

**Issue by sgiacinto** [iliaal/php_excel#280]
Hello,
built on PHP 8.1 
getting:  **Uncaught Error: Call to a member function setHidden() on bool**

when calling:
```
	$ex->getSheetByName("ttemplate")->setHidden(true);
	$ex->getSheetByName("LOOKUPS")->setHidden(true);
```

It worked with previous versions. 
Any idea?

**Comment by johmue** [comment]
Hi,

seems like one of those two calls already fails and returns `false` (instead of a sheet instance):

```php
$ex->getSheetByName("ttemplate");
$ex->getSheetByName("LOOKUPS");
```

... in the subsequent step you are then calling `setHidden()` on `false`.
