### ISSUE TITLE
Pre-build packages for Windows for php 8

### ISSUE THREAD

**Issue by boedyirh** [iliaal/php_excel#286]
Hello, I'm wondering if there are any pre-built packages available for Windows that support either PHP 7 or PHP 8?

This item is already 9 years old and may not be suitable for the latest environment.
https://windows.php.net/downloads/pecl/snaps/excel/20140606/

**Comment by boedyirh** [comment]
https://phpdev.toolsforresearch.com/php-8.2.5-Win32-vs16-x64.zip
https://phpdev.toolsforresearch.com/php-8.1.18-Win32-vs16-x64.zip

**Comment by Jan-E** [comment]
Linked here: https://www.apachelounge.com/viewtopic.php?t=6359
