### ISSUE TITLE
PHP 8 version Error

### ISSUE THREAD

**Issue by mcakmakali** [iliaal/php_excel#287]
Hello,
We are encountering an error with PHP 8 version. When will support for PHP 8 be available or how can we resolve the issue?

```
Fatal error: Array and string offset access syntax with curly braces is no longer supported in 
PHPExcel/Shared/String.php on line 526
```

**Comment by Jan-E** [comment]
Wrong repository. You are referring to https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Shared/String.php#L526

Which is the predecessor of PHPSpreadsheet. Change to PHPSpreadsheet or replace every occurrence of {0}, {1} etc. into [0], [1] etc.
