### ISSUE TITLE
format wasn't inititalized warning

### ISSUE THREAD

**Issue by rbro** [iliaal/php_excel#86]
I am running into an issue where I'm seeing different results if I read a cell's format using cellFormat() or read it via a read() call.  I am running against the latest git code.

There is a reproduce xlsx file at https://drive.google.com/uc?export=download&id=0B37DKbJklxg_WkpPREEtZ0xqU0E.

In the below script, the 2nd echo returns a PHP warning:

```
Warning: ExcelFormat::borderColor(): The format wasn't initialized in /tmp/test.php on line 14
```

Should reading cell formats in these 2 ways give the same results?

```
<?php
$libxl = new ExcelBook('', '', true);

$libxl->loadFile('Book4.xlsx');

$worksheet = $libxl->getSheet(0);

$cell_format = $worksheet->cellFormat(1, 1);

echo $cell_format->borderColor()."\n";

$worksheet->read(1, 1, $cell_format);

echo $cell_format->borderColor()."\n";
```

**Comment by JatinChimote** [comment]
I am also getting this error PHP Warning: ExcelSheet::write(): The format wasn't initialized in file.

// Reference Cell 
$cellFormat = $this->sheet->cellFormat($location[0], $location[1]);
// We have a location so lets write to it.
$this->sheet->write($row, $col, $data, $cellFormat);

Strangely,
It worked for 25 rows and then simply stopped adding any rows, Any idea ?
btw: I am using unlicensed version of LibXL

**Comment by johmue** [comment]
It's very likely related to the trial license. In case you want me to check please provide a complete out of the box running example.
